// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeployerAuditLogsColumns holds the columns for the "deployer_audit_logs" table.
	DeployerAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "audit_id", Type: field.TypeString, Unique: true, Comment: "Unique audit log identifier (UUID)"},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Comment: "Request ID from metadata"},
		{Name: "operation", Type: field.TypeString, Comment: "gRPC operation path"},
		{Name: "service_name", Type: field.TypeString, Comment: "Service name", Default: "deployer-service"},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Comment: "Client ID from certificate CN"},
		{Name: "client_common_name", Type: field.TypeString, Nullable: true, Comment: "Client certificate common name"},
		{Name: "client_organization", Type: field.TypeString, Nullable: true, Comment: "Client certificate organization"},
		{Name: "client_serial_number", Type: field.TypeString, Nullable: true, Comment: "Client certificate serial number"},
		{Name: "is_authenticated", Type: field.TypeBool, Comment: "Whether the client was authenticated via mTLS", Default: false},
		{Name: "success", Type: field.TypeBool, Comment: "Whether the operation succeeded", Default: true},
		{Name: "error_code", Type: field.TypeInt32, Nullable: true, Comment: "Error code if failed"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Comment: "Error message if failed"},
		{Name: "latency_ms", Type: field.TypeInt64, Comment: "Operation latency in milliseconds", Default: 0},
		{Name: "peer_address", Type: field.TypeString, Nullable: true, Comment: "Client IP address"},
		{Name: "geo_location", Type: field.TypeJSON, Nullable: true, Comment: "Geographic location info"},
		{Name: "log_hash", Type: field.TypeString, Nullable: true, Comment: "SHA-256 hash of the log content"},
		{Name: "signature", Type: field.TypeBytes, Nullable: true, Comment: "ECDSA signature for integrity verification"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Additional metadata"},
	}
	// DeployerAuditLogsTable holds the schema information for the "deployer_audit_logs" table.
	DeployerAuditLogsTable = &schema.Table{
		Name:       "deployer_audit_logs",
		Columns:    DeployerAuditLogsColumns,
		PrimaryKey: []*schema.Column{DeployerAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "deployer_auditlog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[4]},
			},
			{
				Name:    "deployer_auditlog_tenant_client",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[4], DeployerAuditLogsColumns[9]},
			},
			{
				Name:    "deployer_auditlog_tenant_operation",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[4], DeployerAuditLogsColumns[7]},
			},
			{
				Name:    "deployer_auditlog_tenant_success",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[4], DeployerAuditLogsColumns[14]},
			},
			{
				Name:    "deployer_auditlog_operation",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[7]},
			},
			{
				Name:    "deployer_auditlog_client_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[9]},
			},
			{
				Name:    "deployer_auditlog_success",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[14]},
			},
			{
				Name:    "deployer_auditlog_peer_address",
				Unique:  false,
				Columns: []*schema.Column{DeployerAuditLogsColumns[18]},
			},
		},
	}
	// DeployerHistoryColumns holds the columns for the "deployer_history" table.
	DeployerHistoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "action", Type: field.TypeEnum, Comment: "Action type", Enums: []string{"ACTION_DEPLOY", "ACTION_VERIFY", "ACTION_ROLLBACK"}},
		{Name: "result", Type: field.TypeEnum, Comment: "Action result", Enums: []string{"RESULT_SUCCESS", "RESULT_FAILURE", "RESULT_PARTIAL"}},
		{Name: "message", Type: field.TypeString, Nullable: true, Comment: "Result message"},
		{Name: "duration_ms", Type: field.TypeInt64, Comment: "Action duration in milliseconds", Default: 0},
		{Name: "details", Type: field.TypeJSON, Nullable: true, Comment: "Additional details"},
		{Name: "job_id", Type: field.TypeString, Comment: "FK to deployment job"},
	}
	// DeployerHistoryTable holds the schema information for the "deployer_history" table.
	DeployerHistoryTable = &schema.Table{
		Name:       "deployer_history",
		Columns:    DeployerHistoryColumns,
		PrimaryKey: []*schema.Column{DeployerHistoryColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deployer_history_deployer_jobs_history",
				Columns:    []*schema.Column{DeployerHistoryColumns[9]},
				RefColumns: []*schema.Column{DeployerJobsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "deploymenthistory_job_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerHistoryColumns[9]},
			},
			{
				Name:    "deploymenthistory_action",
				Unique:  false,
				Columns: []*schema.Column{DeployerHistoryColumns[4]},
			},
			{
				Name:    "deploymenthistory_result",
				Unique:  false,
				Columns: []*schema.Column{DeployerHistoryColumns[5]},
			},
			{
				Name:    "deploymenthistory_create_time",
				Unique:  false,
				Columns: []*schema.Column{DeployerHistoryColumns[1]},
			},
		},
	}
	// DeployerJobsColumns holds the columns for the "deployer_jobs" table.
	DeployerJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "certificate_id", Type: field.TypeString, Comment: "LCM certificate ID"},
		{Name: "certificate_serial", Type: field.TypeString, Nullable: true, Comment: "Certificate serial number"},
		{Name: "status", Type: field.TypeEnum, Comment: "Job status", Enums: []string{"JOB_STATUS_UNSPECIFIED", "JOB_STATUS_PENDING", "JOB_STATUS_PROCESSING", "JOB_STATUS_COMPLETED", "JOB_STATUS_FAILED", "JOB_STATUS_CANCELLED", "JOB_STATUS_RETRYING", "JOB_STATUS_PARTIAL"}, Default: "JOB_STATUS_PENDING"},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Comment: "Status message"},
		{Name: "progress", Type: field.TypeInt32, Comment: "Progress percentage (0-100)", Default: 0},
		{Name: "retry_count", Type: field.TypeInt32, Comment: "Number of retry attempts", Default: 0},
		{Name: "max_retries", Type: field.TypeInt32, Comment: "Maximum retry attempts", Default: 3},
		{Name: "triggered_by", Type: field.TypeEnum, Comment: "How the job was triggered", Enums: []string{"TRIGGER_TYPE_UNSPECIFIED", "TRIGGER_TYPE_MANUAL", "TRIGGER_TYPE_EVENT", "TRIGGER_TYPE_AUTO_RENEWAL"}, Default: "TRIGGER_TYPE_MANUAL"},
		{Name: "result", Type: field.TypeJSON, Nullable: true, Comment: "Deployment result details"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true, Comment: "Job start time"},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true, Comment: "Job completion time"},
		{Name: "next_retry_at", Type: field.TypeTime, Nullable: true, Comment: "Next retry time"},
		{Name: "parent_job_id", Type: field.TypeString, Nullable: true, Comment: "FK to parent job (for child jobs)"},
		{Name: "deployment_target_id", Type: field.TypeString, Nullable: true, Comment: "FK to deployment target group (for parent jobs)"},
		{Name: "target_configuration_id", Type: field.TypeString, Nullable: true, Comment: "FK to target configuration (for child/direct jobs)"},
	}
	// DeployerJobsTable holds the schema information for the "deployer_jobs" table.
	DeployerJobsTable = &schema.Table{
		Name:       "deployer_jobs",
		Columns:    DeployerJobsColumns,
		PrimaryKey: []*schema.Column{DeployerJobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deployer_jobs_deployer_jobs_child_jobs",
				Columns:    []*schema.Column{DeployerJobsColumns[18]},
				RefColumns: []*schema.Column{DeployerJobsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "deployer_jobs_deployer_targets_jobs",
				Columns:    []*schema.Column{DeployerJobsColumns[19]},
				RefColumns: []*schema.Column{DeployerTargetsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "deployer_jobs_deployer_target_configs_jobs",
				Columns:    []*schema.Column{DeployerJobsColumns[20]},
				RefColumns: []*schema.Column{DeployerTargetConfigsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "deploymentjob_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[5]},
			},
			{
				Name:    "deploymentjob_deployment_target_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[19]},
			},
			{
				Name:    "deploymentjob_target_configuration_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[20]},
			},
			{
				Name:    "deploymentjob_parent_job_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[18]},
			},
			{
				Name:    "deploymentjob_certificate_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[6]},
			},
			{
				Name:    "deploymentjob_status",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[8]},
			},
			{
				Name:    "deploymentjob_triggered_by",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[13]},
			},
			{
				Name:    "deploymentjob_create_time",
				Unique:  false,
				Columns: []*schema.Column{DeployerJobsColumns[2]},
			},
		},
	}
	// DeployerTargetsColumns holds the columns for the "deployer_targets" table.
	DeployerTargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Comment: "Target group name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "Target group description"},
		{Name: "auto_deploy_on_renewal", Type: field.TypeBool, Comment: "Auto-deploy certificates on renewal/issuance", Default: false},
		{Name: "certificate_filters", Type: field.TypeJSON, Nullable: true, Comment: "Filters for auto-deployment"},
	}
	// DeployerTargetsTable holds the schema information for the "deployer_targets" table.
	DeployerTargetsTable = &schema.Table{
		Name:       "deployer_targets",
		Columns:    DeployerTargetsColumns,
		PrimaryKey: []*schema.Column{DeployerTargetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "deploymenttarget_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{DeployerTargetsColumns[6], DeployerTargetsColumns[7]},
			},
			{
				Name:    "deploymenttarget_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerTargetsColumns[6]},
			},
			{
				Name:    "deploymenttarget_auto_deploy_on_renewal",
				Unique:  false,
				Columns: []*schema.Column{DeployerTargetsColumns[9]},
			},
		},
	}
	// DeployerTargetConfigsColumns holds the columns for the "deployer_target_configs" table.
	DeployerTargetConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Comment: "Configuration name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "Configuration description"},
		{Name: "provider_type", Type: field.TypeString, Comment: "Provider type (e.g., cloudflare, aws_acm)"},
		{Name: "credentials_encrypted", Type: field.TypeBytes, Comment: "Encrypted provider credentials (JSON)"},
		{Name: "config", Type: field.TypeJSON, Nullable: true, Comment: "Provider-specific configuration"},
		{Name: "status", Type: field.TypeEnum, Comment: "Configuration status", Enums: []string{"CONFIG_STATUS_UNSPECIFIED", "CONFIG_STATUS_ACTIVE", "CONFIG_STATUS_INACTIVE", "CONFIG_STATUS_ERROR"}, Default: "CONFIG_STATUS_ACTIVE"},
		{Name: "status_message", Type: field.TypeString, Nullable: true, Comment: "Status message (e.g., error details)"},
		{Name: "last_deployment_at", Type: field.TypeTime, Nullable: true, Comment: "Last deployment timestamp"},
	}
	// DeployerTargetConfigsTable holds the schema information for the "deployer_target_configs" table.
	DeployerTargetConfigsTable = &schema.Table{
		Name:       "deployer_target_configs",
		Columns:    DeployerTargetConfigsColumns,
		PrimaryKey: []*schema.Column{DeployerTargetConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "targetconfiguration_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{DeployerTargetConfigsColumns[6], DeployerTargetConfigsColumns[7]},
			},
			{
				Name:    "targetconfiguration_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DeployerTargetConfigsColumns[6]},
			},
			{
				Name:    "targetconfiguration_provider_type",
				Unique:  false,
				Columns: []*schema.Column{DeployerTargetConfigsColumns[9]},
			},
			{
				Name:    "targetconfiguration_status",
				Unique:  false,
				Columns: []*schema.Column{DeployerTargetConfigsColumns[12]},
			},
		},
	}
	// DeploymentTargetConfigurationsColumns holds the columns for the "deployment_target_configurations" table.
	DeploymentTargetConfigurationsColumns = []*schema.Column{
		{Name: "deployment_target_id", Type: field.TypeString},
		{Name: "target_configuration_id", Type: field.TypeString},
	}
	// DeploymentTargetConfigurationsTable holds the schema information for the "deployment_target_configurations" table.
	DeploymentTargetConfigurationsTable = &schema.Table{
		Name:       "deployment_target_configurations",
		Columns:    DeploymentTargetConfigurationsColumns,
		PrimaryKey: []*schema.Column{DeploymentTargetConfigurationsColumns[0], DeploymentTargetConfigurationsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deployment_target_configurations_deployment_target_id",
				Columns:    []*schema.Column{DeploymentTargetConfigurationsColumns[0]},
				RefColumns: []*schema.Column{DeployerTargetsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "deployment_target_configurations_target_configuration_id",
				Columns:    []*schema.Column{DeploymentTargetConfigurationsColumns[1]},
				RefColumns: []*schema.Column{DeployerTargetConfigsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeployerAuditLogsTable,
		DeployerHistoryTable,
		DeployerJobsTable,
		DeployerTargetsTable,
		DeployerTargetConfigsTable,
		DeploymentTargetConfigurationsTable,
	}
)

func init() {
	DeployerAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "deployer_audit_logs",
	}
	DeployerHistoryTable.ForeignKeys[0].RefTable = DeployerJobsTable
	DeployerHistoryTable.Annotation = &entsql.Annotation{
		Table: "deployer_history",
	}
	DeployerJobsTable.ForeignKeys[0].RefTable = DeployerJobsTable
	DeployerJobsTable.ForeignKeys[1].RefTable = DeployerTargetsTable
	DeployerJobsTable.ForeignKeys[2].RefTable = DeployerTargetConfigsTable
	DeployerJobsTable.Annotation = &entsql.Annotation{
		Table: "deployer_jobs",
	}
	DeployerTargetsTable.Annotation = &entsql.Annotation{
		Table: "deployer_targets",
	}
	DeployerTargetConfigsTable.Annotation = &entsql.Annotation{
		Table: "deployer_target_configs",
	}
	DeploymentTargetConfigurationsTable.ForeignKeys[0].RefTable = DeployerTargetsTable
	DeploymentTargetConfigurationsTable.ForeignKeys[1].RefTable = DeployerTargetConfigsTable
}
