// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/certificaterenewal"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CertificateRenewalDelete is the builder for deleting a CertificateRenewal entity.
type CertificateRenewalDelete struct {
	config
	hooks    []Hook
	mutation *CertificateRenewalMutation
}

// Where appends a list predicates to the CertificateRenewalDelete builder.
func (_d *CertificateRenewalDelete) Where(ps ...predicate.CertificateRenewal) *CertificateRenewalDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CertificateRenewalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CertificateRenewalDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CertificateRenewalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(certificaterenewal.Table, sqlgraph.NewFieldSpec(certificaterenewal.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CertificateRenewalDeleteOne is the builder for deleting a single CertificateRenewal entity.
type CertificateRenewalDeleteOne struct {
	_d *CertificateRenewalDelete
}

// Where appends a list predicates to the CertificateRenewalDelete builder.
func (_d *CertificateRenewalDeleteOne) Where(ps ...predicate.CertificateRenewal) *CertificateRenewalDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CertificateRenewalDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{certificaterenewal.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CertificateRenewalDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
