// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/certificatepermission"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/issuedcertificate"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/lcmclient"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CertificatePermissionUpdate is the builder for updating CertificatePermission entities.
type CertificatePermissionUpdate struct {
	config
	hooks     []Hook
	mutation  *CertificatePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CertificatePermissionUpdate builder.
func (_u *CertificatePermissionUpdate) Where(ps ...predicate.CertificatePermission) *CertificatePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCertificateID sets the "certificate_id" field.
func (_u *CertificatePermissionUpdate) SetCertificateID(v string) *CertificatePermissionUpdate {
	_u.mutation.SetCertificateID(v)
	return _u
}

// SetNillableCertificateID sets the "certificate_id" field if the given value is not nil.
func (_u *CertificatePermissionUpdate) SetNillableCertificateID(v *string) *CertificatePermissionUpdate {
	if v != nil {
		_u.SetCertificateID(*v)
	}
	return _u
}

// SetGranteeID sets the "grantee_id" field.
func (_u *CertificatePermissionUpdate) SetGranteeID(v uint32) *CertificatePermissionUpdate {
	_u.mutation.SetGranteeID(v)
	return _u
}

// SetNillableGranteeID sets the "grantee_id" field if the given value is not nil.
func (_u *CertificatePermissionUpdate) SetNillableGranteeID(v *uint32) *CertificatePermissionUpdate {
	if v != nil {
		_u.SetGranteeID(*v)
	}
	return _u
}

// SetPermissionType sets the "permission_type" field.
func (_u *CertificatePermissionUpdate) SetPermissionType(v certificatepermission.PermissionType) *CertificatePermissionUpdate {
	_u.mutation.SetPermissionType(v)
	return _u
}

// SetNillablePermissionType sets the "permission_type" field if the given value is not nil.
func (_u *CertificatePermissionUpdate) SetNillablePermissionType(v *certificatepermission.PermissionType) *CertificatePermissionUpdate {
	if v != nil {
		_u.SetPermissionType(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *CertificatePermissionUpdate) SetGrantedBy(v string) *CertificatePermissionUpdate {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *CertificatePermissionUpdate) SetNillableGrantedBy(v *string) *CertificatePermissionUpdate {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CertificatePermissionUpdate) SetExpiresAt(v time.Time) *CertificatePermissionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CertificatePermissionUpdate) SetNillableExpiresAt(v *time.Time) *CertificatePermissionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CertificatePermissionUpdate) ClearExpiresAt() *CertificatePermissionUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificatePermissionUpdate) SetUpdatedAt(v time.Time) *CertificatePermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIssuedCertificateID sets the "issued_certificate" edge to the IssuedCertificate entity by ID.
func (_u *CertificatePermissionUpdate) SetIssuedCertificateID(id string) *CertificatePermissionUpdate {
	_u.mutation.SetIssuedCertificateID(id)
	return _u
}

// SetIssuedCertificate sets the "issued_certificate" edge to the IssuedCertificate entity.
func (_u *CertificatePermissionUpdate) SetIssuedCertificate(v *IssuedCertificate) *CertificatePermissionUpdate {
	return _u.SetIssuedCertificateID(v.ID)
}

// SetGrantee sets the "grantee" edge to the LcmClient entity.
func (_u *CertificatePermissionUpdate) SetGrantee(v *LcmClient) *CertificatePermissionUpdate {
	return _u.SetGranteeID(v.ID)
}

// Mutation returns the CertificatePermissionMutation object of the builder.
func (_u *CertificatePermissionUpdate) Mutation() *CertificatePermissionMutation {
	return _u.mutation
}

// ClearIssuedCertificate clears the "issued_certificate" edge to the IssuedCertificate entity.
func (_u *CertificatePermissionUpdate) ClearIssuedCertificate() *CertificatePermissionUpdate {
	_u.mutation.ClearIssuedCertificate()
	return _u
}

// ClearGrantee clears the "grantee" edge to the LcmClient entity.
func (_u *CertificatePermissionUpdate) ClearGrantee() *CertificatePermissionUpdate {
	_u.mutation.ClearGrantee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CertificatePermissionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificatePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CertificatePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificatePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificatePermissionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if certificatepermission.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized certificatepermission.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := certificatepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificatePermissionUpdate) check() error {
	if v, ok := _u.mutation.CertificateID(); ok {
		if err := certificatepermission.CertificateIDValidator(v); err != nil {
			return &ValidationError{Name: "certificate_id", err: fmt.Errorf(`ent: validator failed for field "CertificatePermission.certificate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PermissionType(); ok {
		if err := certificatepermission.PermissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "permission_type", err: fmt.Errorf(`ent: validator failed for field "CertificatePermission.permission_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantedBy(); ok {
		if err := certificatepermission.GrantedByValidator(v); err != nil {
			return &ValidationError{Name: "granted_by", err: fmt.Errorf(`ent: validator failed for field "CertificatePermission.granted_by": %w`, err)}
		}
	}
	if _u.mutation.IssuedCertificateCleared() && len(_u.mutation.IssuedCertificateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificatePermission.issued_certificate"`)
	}
	if _u.mutation.GranteeCleared() && len(_u.mutation.GranteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificatePermission.grantee"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CertificatePermissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CertificatePermissionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CertificatePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificatepermission.Table, certificatepermission.Columns, sqlgraph.NewFieldSpec(certificatepermission.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(certificatepermission.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PermissionType(); ok {
		_spec.SetField(certificatepermission.FieldPermissionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(certificatepermission.FieldGrantedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(certificatepermission.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(certificatepermission.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificatepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedCertificateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.IssuedCertificateTable,
			Columns: []string{certificatepermission.IssuedCertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issuedcertificate.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuedCertificateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.IssuedCertificateTable,
			Columns: []string{certificatepermission.IssuedCertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issuedcertificate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GranteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.GranteeTable,
			Columns: []string{certificatepermission.GranteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GranteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.GranteeTable,
			Columns: []string{certificatepermission.GranteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificatepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CertificatePermissionUpdateOne is the builder for updating a single CertificatePermission entity.
type CertificatePermissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CertificatePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCertificateID sets the "certificate_id" field.
func (_u *CertificatePermissionUpdateOne) SetCertificateID(v string) *CertificatePermissionUpdateOne {
	_u.mutation.SetCertificateID(v)
	return _u
}

// SetNillableCertificateID sets the "certificate_id" field if the given value is not nil.
func (_u *CertificatePermissionUpdateOne) SetNillableCertificateID(v *string) *CertificatePermissionUpdateOne {
	if v != nil {
		_u.SetCertificateID(*v)
	}
	return _u
}

// SetGranteeID sets the "grantee_id" field.
func (_u *CertificatePermissionUpdateOne) SetGranteeID(v uint32) *CertificatePermissionUpdateOne {
	_u.mutation.SetGranteeID(v)
	return _u
}

// SetNillableGranteeID sets the "grantee_id" field if the given value is not nil.
func (_u *CertificatePermissionUpdateOne) SetNillableGranteeID(v *uint32) *CertificatePermissionUpdateOne {
	if v != nil {
		_u.SetGranteeID(*v)
	}
	return _u
}

// SetPermissionType sets the "permission_type" field.
func (_u *CertificatePermissionUpdateOne) SetPermissionType(v certificatepermission.PermissionType) *CertificatePermissionUpdateOne {
	_u.mutation.SetPermissionType(v)
	return _u
}

// SetNillablePermissionType sets the "permission_type" field if the given value is not nil.
func (_u *CertificatePermissionUpdateOne) SetNillablePermissionType(v *certificatepermission.PermissionType) *CertificatePermissionUpdateOne {
	if v != nil {
		_u.SetPermissionType(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *CertificatePermissionUpdateOne) SetGrantedBy(v string) *CertificatePermissionUpdateOne {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *CertificatePermissionUpdateOne) SetNillableGrantedBy(v *string) *CertificatePermissionUpdateOne {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CertificatePermissionUpdateOne) SetExpiresAt(v time.Time) *CertificatePermissionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CertificatePermissionUpdateOne) SetNillableExpiresAt(v *time.Time) *CertificatePermissionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CertificatePermissionUpdateOne) ClearExpiresAt() *CertificatePermissionUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificatePermissionUpdateOne) SetUpdatedAt(v time.Time) *CertificatePermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIssuedCertificateID sets the "issued_certificate" edge to the IssuedCertificate entity by ID.
func (_u *CertificatePermissionUpdateOne) SetIssuedCertificateID(id string) *CertificatePermissionUpdateOne {
	_u.mutation.SetIssuedCertificateID(id)
	return _u
}

// SetIssuedCertificate sets the "issued_certificate" edge to the IssuedCertificate entity.
func (_u *CertificatePermissionUpdateOne) SetIssuedCertificate(v *IssuedCertificate) *CertificatePermissionUpdateOne {
	return _u.SetIssuedCertificateID(v.ID)
}

// SetGrantee sets the "grantee" edge to the LcmClient entity.
func (_u *CertificatePermissionUpdateOne) SetGrantee(v *LcmClient) *CertificatePermissionUpdateOne {
	return _u.SetGranteeID(v.ID)
}

// Mutation returns the CertificatePermissionMutation object of the builder.
func (_u *CertificatePermissionUpdateOne) Mutation() *CertificatePermissionMutation {
	return _u.mutation
}

// ClearIssuedCertificate clears the "issued_certificate" edge to the IssuedCertificate entity.
func (_u *CertificatePermissionUpdateOne) ClearIssuedCertificate() *CertificatePermissionUpdateOne {
	_u.mutation.ClearIssuedCertificate()
	return _u
}

// ClearGrantee clears the "grantee" edge to the LcmClient entity.
func (_u *CertificatePermissionUpdateOne) ClearGrantee() *CertificatePermissionUpdateOne {
	_u.mutation.ClearGrantee()
	return _u
}

// Where appends a list predicates to the CertificatePermissionUpdate builder.
func (_u *CertificatePermissionUpdateOne) Where(ps ...predicate.CertificatePermission) *CertificatePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CertificatePermissionUpdateOne) Select(field string, fields ...string) *CertificatePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CertificatePermission entity.
func (_u *CertificatePermissionUpdateOne) Save(ctx context.Context) (*CertificatePermission, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificatePermissionUpdateOne) SaveX(ctx context.Context) *CertificatePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CertificatePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificatePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificatePermissionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if certificatepermission.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized certificatepermission.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := certificatepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificatePermissionUpdateOne) check() error {
	if v, ok := _u.mutation.CertificateID(); ok {
		if err := certificatepermission.CertificateIDValidator(v); err != nil {
			return &ValidationError{Name: "certificate_id", err: fmt.Errorf(`ent: validator failed for field "CertificatePermission.certificate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PermissionType(); ok {
		if err := certificatepermission.PermissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "permission_type", err: fmt.Errorf(`ent: validator failed for field "CertificatePermission.permission_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GrantedBy(); ok {
		if err := certificatepermission.GrantedByValidator(v); err != nil {
			return &ValidationError{Name: "granted_by", err: fmt.Errorf(`ent: validator failed for field "CertificatePermission.granted_by": %w`, err)}
		}
	}
	if _u.mutation.IssuedCertificateCleared() && len(_u.mutation.IssuedCertificateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificatePermission.issued_certificate"`)
	}
	if _u.mutation.GranteeCleared() && len(_u.mutation.GranteeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CertificatePermission.grantee"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CertificatePermissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CertificatePermissionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CertificatePermissionUpdateOne) sqlSave(ctx context.Context) (_node *CertificatePermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificatepermission.Table, certificatepermission.Columns, sqlgraph.NewFieldSpec(certificatepermission.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CertificatePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, certificatepermission.FieldID)
		for _, f := range fields {
			if !certificatepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != certificatepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(certificatepermission.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.PermissionType(); ok {
		_spec.SetField(certificatepermission.FieldPermissionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(certificatepermission.FieldGrantedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(certificatepermission.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(certificatepermission.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificatepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedCertificateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.IssuedCertificateTable,
			Columns: []string{certificatepermission.IssuedCertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issuedcertificate.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuedCertificateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.IssuedCertificateTable,
			Columns: []string{certificatepermission.IssuedCertificateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(issuedcertificate.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GranteeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.GranteeTable,
			Columns: []string{certificatepermission.GranteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GranteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   certificatepermission.GranteeTable,
			Columns: []string{certificatepermission.GranteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CertificatePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificatepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
