// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/lcmclient"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/mtlscertificaterequest"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// MtlsCertificateRequestUpdate is the builder for updating MtlsCertificateRequest entities.
type MtlsCertificateRequestUpdate struct {
	config
	hooks     []Hook
	mutation  *MtlsCertificateRequestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MtlsCertificateRequestUpdate builder.
func (_u *MtlsCertificateRequestUpdate) Where(ps ...predicate.MtlsCertificateRequest) *MtlsCertificateRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *MtlsCertificateRequestUpdate) SetCreateBy(v uint32) *MtlsCertificateRequestUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableCreateBy(v *uint32) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *MtlsCertificateRequestUpdate) AddCreateBy(v int32) *MtlsCertificateRequestUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *MtlsCertificateRequestUpdate) ClearCreateBy() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *MtlsCertificateRequestUpdate) SetUpdateBy(v uint32) *MtlsCertificateRequestUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableUpdateBy(v *uint32) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *MtlsCertificateRequestUpdate) AddUpdateBy(v int32) *MtlsCertificateRequestUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *MtlsCertificateRequestUpdate) ClearUpdateBy() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *MtlsCertificateRequestUpdate) SetUpdateTime(v time.Time) *MtlsCertificateRequestUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableUpdateTime(v *time.Time) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *MtlsCertificateRequestUpdate) ClearUpdateTime() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *MtlsCertificateRequestUpdate) SetDeleteTime(v time.Time) *MtlsCertificateRequestUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableDeleteTime(v *time.Time) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *MtlsCertificateRequestUpdate) ClearDeleteTime() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *MtlsCertificateRequestUpdate) SetRequestID(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableRequestID(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *MtlsCertificateRequestUpdate) SetClientID(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableClientID(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetCommonName sets the "common_name" field.
func (_u *MtlsCertificateRequestUpdate) SetCommonName(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetCommonName(v)
	return _u
}

// SetNillableCommonName sets the "common_name" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableCommonName(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetCommonName(*v)
	}
	return _u
}

// ClearCommonName clears the value of the "common_name" field.
func (_u *MtlsCertificateRequestUpdate) ClearCommonName() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearCommonName()
	return _u
}

// SetCsrPem sets the "csr_pem" field.
func (_u *MtlsCertificateRequestUpdate) SetCsrPem(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetCsrPem(v)
	return _u
}

// SetNillableCsrPem sets the "csr_pem" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableCsrPem(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetCsrPem(*v)
	}
	return _u
}

// ClearCsrPem clears the value of the "csr_pem" field.
func (_u *MtlsCertificateRequestUpdate) ClearCsrPem() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearCsrPem()
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *MtlsCertificateRequestUpdate) SetPublicKey(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillablePublicKey(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// ClearPublicKey clears the value of the "public_key" field.
func (_u *MtlsCertificateRequestUpdate) ClearPublicKey() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearPublicKey()
	return _u
}

// SetDNSNames sets the "dns_names" field.
func (_u *MtlsCertificateRequestUpdate) SetDNSNames(v []string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetDNSNames(v)
	return _u
}

// AppendDNSNames appends value to the "dns_names" field.
func (_u *MtlsCertificateRequestUpdate) AppendDNSNames(v []string) *MtlsCertificateRequestUpdate {
	_u.mutation.AppendDNSNames(v)
	return _u
}

// ClearDNSNames clears the value of the "dns_names" field.
func (_u *MtlsCertificateRequestUpdate) ClearDNSNames() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearDNSNames()
	return _u
}

// SetIPAddresses sets the "ip_addresses" field.
func (_u *MtlsCertificateRequestUpdate) SetIPAddresses(v []string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetIPAddresses(v)
	return _u
}

// AppendIPAddresses appends value to the "ip_addresses" field.
func (_u *MtlsCertificateRequestUpdate) AppendIPAddresses(v []string) *MtlsCertificateRequestUpdate {
	_u.mutation.AppendIPAddresses(v)
	return _u
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (_u *MtlsCertificateRequestUpdate) ClearIPAddresses() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearIPAddresses()
	return _u
}

// SetIssuerName sets the "issuer_name" field.
func (_u *MtlsCertificateRequestUpdate) SetIssuerName(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetIssuerName(v)
	return _u
}

// SetNillableIssuerName sets the "issuer_name" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableIssuerName(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetIssuerName(*v)
	}
	return _u
}

// ClearIssuerName clears the value of the "issuer_name" field.
func (_u *MtlsCertificateRequestUpdate) ClearIssuerName() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearIssuerName()
	return _u
}

// SetCertType sets the "cert_type" field.
func (_u *MtlsCertificateRequestUpdate) SetCertType(v mtlscertificaterequest.CertType) *MtlsCertificateRequestUpdate {
	_u.mutation.SetCertType(v)
	return _u
}

// SetNillableCertType sets the "cert_type" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableCertType(v *mtlscertificaterequest.CertType) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetCertType(*v)
	}
	return _u
}

// ClearCertType clears the value of the "cert_type" field.
func (_u *MtlsCertificateRequestUpdate) ClearCertType() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearCertType()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MtlsCertificateRequestUpdate) SetStatus(v mtlscertificaterequest.Status) *MtlsCertificateRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableStatus(v *mtlscertificaterequest.Status) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *MtlsCertificateRequestUpdate) ClearStatus() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *MtlsCertificateRequestUpdate) SetValidityDays(v int32) *MtlsCertificateRequestUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableValidityDays(v *int32) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *MtlsCertificateRequestUpdate) AddValidityDays(v int32) *MtlsCertificateRequestUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *MtlsCertificateRequestUpdate) ClearValidityDays() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *MtlsCertificateRequestUpdate) SetRejectReason(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableRejectReason(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *MtlsCertificateRequestUpdate) ClearRejectReason() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MtlsCertificateRequestUpdate) SetMetadata(v map[string]string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MtlsCertificateRequestUpdate) ClearMetadata() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *MtlsCertificateRequestUpdate) SetNotes(v string) *MtlsCertificateRequestUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableNotes(v *string) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *MtlsCertificateRequestUpdate) ClearNotes() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *MtlsCertificateRequestUpdate) SetApprovedBy(v uint32) *MtlsCertificateRequestUpdate {
	_u.mutation.ResetApprovedBy()
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableApprovedBy(v *uint32) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// AddApprovedBy adds value to the "approved_by" field.
func (_u *MtlsCertificateRequestUpdate) AddApprovedBy(v int32) *MtlsCertificateRequestUpdate {
	_u.mutation.AddApprovedBy(v)
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *MtlsCertificateRequestUpdate) ClearApprovedBy() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearApprovedBy()
	return _u
}

// SetRejectedBy sets the "rejected_by" field.
func (_u *MtlsCertificateRequestUpdate) SetRejectedBy(v uint32) *MtlsCertificateRequestUpdate {
	_u.mutation.ResetRejectedBy()
	_u.mutation.SetRejectedBy(v)
	return _u
}

// SetNillableRejectedBy sets the "rejected_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableRejectedBy(v *uint32) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetRejectedBy(*v)
	}
	return _u
}

// AddRejectedBy adds value to the "rejected_by" field.
func (_u *MtlsCertificateRequestUpdate) AddRejectedBy(v int32) *MtlsCertificateRequestUpdate {
	_u.mutation.AddRejectedBy(v)
	return _u
}

// ClearRejectedBy clears the value of the "rejected_by" field.
func (_u *MtlsCertificateRequestUpdate) ClearRejectedBy() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearRejectedBy()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *MtlsCertificateRequestUpdate) SetApprovedAt(v time.Time) *MtlsCertificateRequestUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableApprovedAt(v *time.Time) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *MtlsCertificateRequestUpdate) ClearApprovedAt() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetRejectedAt sets the "rejected_at" field.
func (_u *MtlsCertificateRequestUpdate) SetRejectedAt(v time.Time) *MtlsCertificateRequestUpdate {
	_u.mutation.SetRejectedAt(v)
	return _u
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableRejectedAt(v *time.Time) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetRejectedAt(*v)
	}
	return _u
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (_u *MtlsCertificateRequestUpdate) ClearRejectedAt() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearRejectedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MtlsCertificateRequestUpdate) SetExpiresAt(v time.Time) *MtlsCertificateRequestUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableExpiresAt(v *time.Time) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MtlsCertificateRequestUpdate) ClearExpiresAt() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCertificateSerial sets the "certificate_serial" field.
func (_u *MtlsCertificateRequestUpdate) SetCertificateSerial(v int64) *MtlsCertificateRequestUpdate {
	_u.mutation.ResetCertificateSerial()
	_u.mutation.SetCertificateSerial(v)
	return _u
}

// SetNillableCertificateSerial sets the "certificate_serial" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableCertificateSerial(v *int64) *MtlsCertificateRequestUpdate {
	if v != nil {
		_u.SetCertificateSerial(*v)
	}
	return _u
}

// AddCertificateSerial adds value to the "certificate_serial" field.
func (_u *MtlsCertificateRequestUpdate) AddCertificateSerial(v int64) *MtlsCertificateRequestUpdate {
	_u.mutation.AddCertificateSerial(v)
	return _u
}

// ClearCertificateSerial clears the value of the "certificate_serial" field.
func (_u *MtlsCertificateRequestUpdate) ClearCertificateSerial() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearCertificateSerial()
	return _u
}

// SetLcmClientID sets the "lcm_client" edge to the LcmClient entity by ID.
func (_u *MtlsCertificateRequestUpdate) SetLcmClientID(id uint32) *MtlsCertificateRequestUpdate {
	_u.mutation.SetLcmClientID(id)
	return _u
}

// SetNillableLcmClientID sets the "lcm_client" edge to the LcmClient entity by ID if the given value is not nil.
func (_u *MtlsCertificateRequestUpdate) SetNillableLcmClientID(id *uint32) *MtlsCertificateRequestUpdate {
	if id != nil {
		_u = _u.SetLcmClientID(*id)
	}
	return _u
}

// SetLcmClient sets the "lcm_client" edge to the LcmClient entity.
func (_u *MtlsCertificateRequestUpdate) SetLcmClient(v *LcmClient) *MtlsCertificateRequestUpdate {
	return _u.SetLcmClientID(v.ID)
}

// Mutation returns the MtlsCertificateRequestMutation object of the builder.
func (_u *MtlsCertificateRequestUpdate) Mutation() *MtlsCertificateRequestMutation {
	return _u.mutation
}

// ClearLcmClient clears the "lcm_client" edge to the LcmClient entity.
func (_u *MtlsCertificateRequestUpdate) ClearLcmClient() *MtlsCertificateRequestUpdate {
	_u.mutation.ClearLcmClient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MtlsCertificateRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MtlsCertificateRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MtlsCertificateRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MtlsCertificateRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MtlsCertificateRequestUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := mtlscertificaterequest.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := mtlscertificaterequest.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CertType(); ok {
		if err := mtlscertificaterequest.CertTypeValidator(v); err != nil {
			return &ValidationError{Name: "cert_type", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.cert_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mtlscertificaterequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MtlsCertificateRequestUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MtlsCertificateRequestUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MtlsCertificateRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mtlscertificaterequest.Table, mtlscertificaterequest.Columns, sqlgraph.NewFieldSpec(mtlscertificaterequest.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(mtlscertificaterequest.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(mtlscertificaterequest.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(mtlscertificaterequest.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommonName(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCommonName, field.TypeString, value)
	}
	if _u.mutation.CommonNameCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCommonName, field.TypeString)
	}
	if value, ok := _u.mutation.CsrPem(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCsrPem, field.TypeString, value)
	}
	if _u.mutation.CsrPemCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCsrPem, field.TypeString)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(mtlscertificaterequest.FieldPublicKey, field.TypeString, value)
	}
	if _u.mutation.PublicKeyCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldPublicKey, field.TypeString)
	}
	if value, ok := _u.mutation.DNSNames(); ok {
		_spec.SetField(mtlscertificaterequest.FieldDNSNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDNSNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mtlscertificaterequest.FieldDNSNames, value)
		})
	}
	if _u.mutation.DNSNamesCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldDNSNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddresses(); ok {
		_spec.SetField(mtlscertificaterequest.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mtlscertificaterequest.FieldIPAddresses, value)
		})
	}
	if _u.mutation.IPAddressesCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.IssuerName(); ok {
		_spec.SetField(mtlscertificaterequest.FieldIssuerName, field.TypeString, value)
	}
	if _u.mutation.IssuerNameCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldIssuerName, field.TypeString)
	}
	if value, ok := _u.mutation.CertType(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCertType, field.TypeEnum, value)
	}
	if _u.mutation.CertTypeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCertType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mtlscertificaterequest.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(mtlscertificaterequest.FieldValidityDays, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(mtlscertificaterequest.FieldValidityDays, field.TypeInt32, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldValidityDays, field.TypeInt32)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(mtlscertificaterequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(mtlscertificaterequest.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldApprovedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedApprovedBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldApprovedBy, field.TypeUint32, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldApprovedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.RejectedBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRejectedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRejectedBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldRejectedBy, field.TypeUint32, value)
	}
	if _u.mutation.RejectedByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldRejectedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(mtlscertificaterequest.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedAt(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRejectedAt, field.TypeTime, value)
	}
	if _u.mutation.RejectedAtCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mtlscertificaterequest.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertificateSerial(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCertificateSerial, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCertificateSerial(); ok {
		_spec.AddField(mtlscertificaterequest.FieldCertificateSerial, field.TypeInt64, value)
	}
	if _u.mutation.CertificateSerialCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCertificateSerial, field.TypeInt64)
	}
	if _u.mutation.LcmClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mtlscertificaterequest.LcmClientTable,
			Columns: []string{mtlscertificaterequest.LcmClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LcmClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mtlscertificaterequest.LcmClientTable,
			Columns: []string{mtlscertificaterequest.LcmClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mtlscertificaterequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MtlsCertificateRequestUpdateOne is the builder for updating a single MtlsCertificateRequest entity.
type MtlsCertificateRequestUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MtlsCertificateRequestMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *MtlsCertificateRequestUpdateOne) SetCreateBy(v uint32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableCreateBy(v *uint32) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *MtlsCertificateRequestUpdateOne) AddCreateBy(v int32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearCreateBy() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *MtlsCertificateRequestUpdateOne) SetUpdateBy(v uint32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableUpdateBy(v *uint32) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *MtlsCertificateRequestUpdateOne) AddUpdateBy(v int32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearUpdateBy() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *MtlsCertificateRequestUpdateOne) SetUpdateTime(v time.Time) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableUpdateTime(v *time.Time) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearUpdateTime() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *MtlsCertificateRequestUpdateOne) SetDeleteTime(v time.Time) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableDeleteTime(v *time.Time) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearDeleteTime() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *MtlsCertificateRequestUpdateOne) SetRequestID(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableRequestID(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *MtlsCertificateRequestUpdateOne) SetClientID(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableClientID(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetCommonName sets the "common_name" field.
func (_u *MtlsCertificateRequestUpdateOne) SetCommonName(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetCommonName(v)
	return _u
}

// SetNillableCommonName sets the "common_name" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableCommonName(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetCommonName(*v)
	}
	return _u
}

// ClearCommonName clears the value of the "common_name" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearCommonName() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearCommonName()
	return _u
}

// SetCsrPem sets the "csr_pem" field.
func (_u *MtlsCertificateRequestUpdateOne) SetCsrPem(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetCsrPem(v)
	return _u
}

// SetNillableCsrPem sets the "csr_pem" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableCsrPem(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetCsrPem(*v)
	}
	return _u
}

// ClearCsrPem clears the value of the "csr_pem" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearCsrPem() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearCsrPem()
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *MtlsCertificateRequestUpdateOne) SetPublicKey(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillablePublicKey(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// ClearPublicKey clears the value of the "public_key" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearPublicKey() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearPublicKey()
	return _u
}

// SetDNSNames sets the "dns_names" field.
func (_u *MtlsCertificateRequestUpdateOne) SetDNSNames(v []string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetDNSNames(v)
	return _u
}

// AppendDNSNames appends value to the "dns_names" field.
func (_u *MtlsCertificateRequestUpdateOne) AppendDNSNames(v []string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AppendDNSNames(v)
	return _u
}

// ClearDNSNames clears the value of the "dns_names" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearDNSNames() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearDNSNames()
	return _u
}

// SetIPAddresses sets the "ip_addresses" field.
func (_u *MtlsCertificateRequestUpdateOne) SetIPAddresses(v []string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetIPAddresses(v)
	return _u
}

// AppendIPAddresses appends value to the "ip_addresses" field.
func (_u *MtlsCertificateRequestUpdateOne) AppendIPAddresses(v []string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AppendIPAddresses(v)
	return _u
}

// ClearIPAddresses clears the value of the "ip_addresses" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearIPAddresses() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearIPAddresses()
	return _u
}

// SetIssuerName sets the "issuer_name" field.
func (_u *MtlsCertificateRequestUpdateOne) SetIssuerName(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetIssuerName(v)
	return _u
}

// SetNillableIssuerName sets the "issuer_name" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableIssuerName(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetIssuerName(*v)
	}
	return _u
}

// ClearIssuerName clears the value of the "issuer_name" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearIssuerName() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearIssuerName()
	return _u
}

// SetCertType sets the "cert_type" field.
func (_u *MtlsCertificateRequestUpdateOne) SetCertType(v mtlscertificaterequest.CertType) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetCertType(v)
	return _u
}

// SetNillableCertType sets the "cert_type" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableCertType(v *mtlscertificaterequest.CertType) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetCertType(*v)
	}
	return _u
}

// ClearCertType clears the value of the "cert_type" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearCertType() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearCertType()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MtlsCertificateRequestUpdateOne) SetStatus(v mtlscertificaterequest.Status) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableStatus(v *mtlscertificaterequest.Status) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearStatus() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *MtlsCertificateRequestUpdateOne) SetValidityDays(v int32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableValidityDays(v *int32) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *MtlsCertificateRequestUpdateOne) AddValidityDays(v int32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearValidityDays() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *MtlsCertificateRequestUpdateOne) SetRejectReason(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableRejectReason(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearRejectReason() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MtlsCertificateRequestUpdateOne) SetMetadata(v map[string]string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearMetadata() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *MtlsCertificateRequestUpdateOne) SetNotes(v string) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableNotes(v *string) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearNotes() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetApprovedBy sets the "approved_by" field.
func (_u *MtlsCertificateRequestUpdateOne) SetApprovedBy(v uint32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.ResetApprovedBy()
	_u.mutation.SetApprovedBy(v)
	return _u
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableApprovedBy(v *uint32) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetApprovedBy(*v)
	}
	return _u
}

// AddApprovedBy adds value to the "approved_by" field.
func (_u *MtlsCertificateRequestUpdateOne) AddApprovedBy(v int32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AddApprovedBy(v)
	return _u
}

// ClearApprovedBy clears the value of the "approved_by" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearApprovedBy() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearApprovedBy()
	return _u
}

// SetRejectedBy sets the "rejected_by" field.
func (_u *MtlsCertificateRequestUpdateOne) SetRejectedBy(v uint32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.ResetRejectedBy()
	_u.mutation.SetRejectedBy(v)
	return _u
}

// SetNillableRejectedBy sets the "rejected_by" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableRejectedBy(v *uint32) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetRejectedBy(*v)
	}
	return _u
}

// AddRejectedBy adds value to the "rejected_by" field.
func (_u *MtlsCertificateRequestUpdateOne) AddRejectedBy(v int32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AddRejectedBy(v)
	return _u
}

// ClearRejectedBy clears the value of the "rejected_by" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearRejectedBy() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearRejectedBy()
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *MtlsCertificateRequestUpdateOne) SetApprovedAt(v time.Time) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableApprovedAt(v *time.Time) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearApprovedAt() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetRejectedAt sets the "rejected_at" field.
func (_u *MtlsCertificateRequestUpdateOne) SetRejectedAt(v time.Time) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetRejectedAt(v)
	return _u
}

// SetNillableRejectedAt sets the "rejected_at" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableRejectedAt(v *time.Time) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetRejectedAt(*v)
	}
	return _u
}

// ClearRejectedAt clears the value of the "rejected_at" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearRejectedAt() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearRejectedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MtlsCertificateRequestUpdateOne) SetExpiresAt(v time.Time) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableExpiresAt(v *time.Time) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearExpiresAt() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCertificateSerial sets the "certificate_serial" field.
func (_u *MtlsCertificateRequestUpdateOne) SetCertificateSerial(v int64) *MtlsCertificateRequestUpdateOne {
	_u.mutation.ResetCertificateSerial()
	_u.mutation.SetCertificateSerial(v)
	return _u
}

// SetNillableCertificateSerial sets the "certificate_serial" field if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableCertificateSerial(v *int64) *MtlsCertificateRequestUpdateOne {
	if v != nil {
		_u.SetCertificateSerial(*v)
	}
	return _u
}

// AddCertificateSerial adds value to the "certificate_serial" field.
func (_u *MtlsCertificateRequestUpdateOne) AddCertificateSerial(v int64) *MtlsCertificateRequestUpdateOne {
	_u.mutation.AddCertificateSerial(v)
	return _u
}

// ClearCertificateSerial clears the value of the "certificate_serial" field.
func (_u *MtlsCertificateRequestUpdateOne) ClearCertificateSerial() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearCertificateSerial()
	return _u
}

// SetLcmClientID sets the "lcm_client" edge to the LcmClient entity by ID.
func (_u *MtlsCertificateRequestUpdateOne) SetLcmClientID(id uint32) *MtlsCertificateRequestUpdateOne {
	_u.mutation.SetLcmClientID(id)
	return _u
}

// SetNillableLcmClientID sets the "lcm_client" edge to the LcmClient entity by ID if the given value is not nil.
func (_u *MtlsCertificateRequestUpdateOne) SetNillableLcmClientID(id *uint32) *MtlsCertificateRequestUpdateOne {
	if id != nil {
		_u = _u.SetLcmClientID(*id)
	}
	return _u
}

// SetLcmClient sets the "lcm_client" edge to the LcmClient entity.
func (_u *MtlsCertificateRequestUpdateOne) SetLcmClient(v *LcmClient) *MtlsCertificateRequestUpdateOne {
	return _u.SetLcmClientID(v.ID)
}

// Mutation returns the MtlsCertificateRequestMutation object of the builder.
func (_u *MtlsCertificateRequestUpdateOne) Mutation() *MtlsCertificateRequestMutation {
	return _u.mutation
}

// ClearLcmClient clears the "lcm_client" edge to the LcmClient entity.
func (_u *MtlsCertificateRequestUpdateOne) ClearLcmClient() *MtlsCertificateRequestUpdateOne {
	_u.mutation.ClearLcmClient()
	return _u
}

// Where appends a list predicates to the MtlsCertificateRequestUpdate builder.
func (_u *MtlsCertificateRequestUpdateOne) Where(ps ...predicate.MtlsCertificateRequest) *MtlsCertificateRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MtlsCertificateRequestUpdateOne) Select(field string, fields ...string) *MtlsCertificateRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MtlsCertificateRequest entity.
func (_u *MtlsCertificateRequestUpdateOne) Save(ctx context.Context) (*MtlsCertificateRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MtlsCertificateRequestUpdateOne) SaveX(ctx context.Context) *MtlsCertificateRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MtlsCertificateRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MtlsCertificateRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MtlsCertificateRequestUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := mtlscertificaterequest.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := mtlscertificaterequest.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CertType(); ok {
		if err := mtlscertificaterequest.CertTypeValidator(v); err != nil {
			return &ValidationError{Name: "cert_type", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.cert_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mtlscertificaterequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MtlsCertificateRequest.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MtlsCertificateRequestUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MtlsCertificateRequestUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MtlsCertificateRequestUpdateOne) sqlSave(ctx context.Context) (_node *MtlsCertificateRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mtlscertificaterequest.Table, mtlscertificaterequest.Columns, sqlgraph.NewFieldSpec(mtlscertificaterequest.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MtlsCertificateRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mtlscertificaterequest.FieldID)
		for _, f := range fields {
			if !mtlscertificaterequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mtlscertificaterequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(mtlscertificaterequest.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(mtlscertificaterequest.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(mtlscertificaterequest.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommonName(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCommonName, field.TypeString, value)
	}
	if _u.mutation.CommonNameCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCommonName, field.TypeString)
	}
	if value, ok := _u.mutation.CsrPem(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCsrPem, field.TypeString, value)
	}
	if _u.mutation.CsrPemCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCsrPem, field.TypeString)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(mtlscertificaterequest.FieldPublicKey, field.TypeString, value)
	}
	if _u.mutation.PublicKeyCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldPublicKey, field.TypeString)
	}
	if value, ok := _u.mutation.DNSNames(); ok {
		_spec.SetField(mtlscertificaterequest.FieldDNSNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDNSNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mtlscertificaterequest.FieldDNSNames, value)
		})
	}
	if _u.mutation.DNSNamesCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldDNSNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddresses(); ok {
		_spec.SetField(mtlscertificaterequest.FieldIPAddresses, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAddresses(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mtlscertificaterequest.FieldIPAddresses, value)
		})
	}
	if _u.mutation.IPAddressesCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldIPAddresses, field.TypeJSON)
	}
	if value, ok := _u.mutation.IssuerName(); ok {
		_spec.SetField(mtlscertificaterequest.FieldIssuerName, field.TypeString, value)
	}
	if _u.mutation.IssuerNameCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldIssuerName, field.TypeString)
	}
	if value, ok := _u.mutation.CertType(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCertType, field.TypeEnum, value)
	}
	if _u.mutation.CertTypeCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCertType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mtlscertificaterequest.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(mtlscertificaterequest.FieldValidityDays, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(mtlscertificaterequest.FieldValidityDays, field.TypeInt32, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldValidityDays, field.TypeInt32)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(mtlscertificaterequest.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(mtlscertificaterequest.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ApprovedBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldApprovedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedApprovedBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldApprovedBy, field.TypeUint32, value)
	}
	if _u.mutation.ApprovedByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldApprovedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.RejectedBy(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRejectedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRejectedBy(); ok {
		_spec.AddField(mtlscertificaterequest.FieldRejectedBy, field.TypeUint32, value)
	}
	if _u.mutation.RejectedByCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldRejectedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(mtlscertificaterequest.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RejectedAt(); ok {
		_spec.SetField(mtlscertificaterequest.FieldRejectedAt, field.TypeTime, value)
	}
	if _u.mutation.RejectedAtCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldRejectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mtlscertificaterequest.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CertificateSerial(); ok {
		_spec.SetField(mtlscertificaterequest.FieldCertificateSerial, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCertificateSerial(); ok {
		_spec.AddField(mtlscertificaterequest.FieldCertificateSerial, field.TypeInt64, value)
	}
	if _u.mutation.CertificateSerialCleared() {
		_spec.ClearField(mtlscertificaterequest.FieldCertificateSerial, field.TypeInt64)
	}
	if _u.mutation.LcmClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mtlscertificaterequest.LcmClientTable,
			Columns: []string{mtlscertificaterequest.LcmClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LcmClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mtlscertificaterequest.LcmClientTable,
			Columns: []string{mtlscertificaterequest.LcmClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lcmclient.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MtlsCertificateRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mtlscertificaterequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
