// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/selfsignedissuer"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SelfSignedIssuerDelete is the builder for deleting a SelfSignedIssuer entity.
type SelfSignedIssuerDelete struct {
	config
	hooks    []Hook
	mutation *SelfSignedIssuerMutation
}

// Where appends a list predicates to the SelfSignedIssuerDelete builder.
func (_d *SelfSignedIssuerDelete) Where(ps ...predicate.SelfSignedIssuer) *SelfSignedIssuerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SelfSignedIssuerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SelfSignedIssuerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SelfSignedIssuerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(selfsignedissuer.Table, sqlgraph.NewFieldSpec(selfsignedissuer.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SelfSignedIssuerDeleteOne is the builder for deleting a single SelfSignedIssuer entity.
type SelfSignedIssuerDeleteOne struct {
	_d *SelfSignedIssuerDelete
}

// Where appends a list predicates to the SelfSignedIssuerDelete builder.
func (_d *SelfSignedIssuerDeleteOne) Where(ps ...predicate.SelfSignedIssuer) *SelfSignedIssuerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SelfSignedIssuerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{selfsignedissuer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SelfSignedIssuerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
