// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/tenantsecret"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TenantSecret is the model entity for the TenantSecret schema.
type TenantSecret struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// Tenant ID this secret belongs to
	TenantID uint32 `json:"tenant_id,omitempty"`
	// SHA-256 hash of the shared secret
	SecretHash string `json:"secret_hash,omitempty"`
	// Description of this secret
	Description string `json:"description,omitempty"`
	// Secret status
	Status tenantsecret.Status `json:"status,omitempty"`
	// Expiration time for this secret
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantSecret) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantsecret.FieldID, tenantsecret.FieldCreateBy, tenantsecret.FieldUpdateBy, tenantsecret.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case tenantsecret.FieldSecretHash, tenantsecret.FieldDescription, tenantsecret.FieldStatus:
			values[i] = new(sql.NullString)
		case tenantsecret.FieldCreateTime, tenantsecret.FieldUpdateTime, tenantsecret.FieldDeleteTime, tenantsecret.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantSecret fields.
func (_m *TenantSecret) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantsecret.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case tenantsecret.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case tenantsecret.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case tenantsecret.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case tenantsecret.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case tenantsecret.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case tenantsecret.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint32(value.Int64)
			}
		case tenantsecret.FieldSecretHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_hash", values[i])
			} else if value.Valid {
				_m.SecretHash = value.String
			}
		case tenantsecret.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case tenantsecret.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = tenantsecret.Status(value.String)
			}
		case tenantsecret.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantSecret.
// This includes values selected through modifiers, order, etc.
func (_m *TenantSecret) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TenantSecret.
// Note that you need to call TenantSecret.Unwrap() before calling this method if this TenantSecret
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TenantSecret) Update() *TenantSecretUpdateOne {
	return NewTenantSecretClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TenantSecret entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TenantSecret) Unwrap() *TenantSecret {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantSecret is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TenantSecret) String() string {
	var builder strings.Builder
	builder.WriteString("TenantSecret(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("secret_hash=")
	builder.WriteString(_m.SecretHash)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TenantSecrets is a parsable slice of TenantSecret.
type TenantSecrets []*TenantSecret
