// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/data/ent/deploymenthistory"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/data/ent/deploymentjob"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/data/ent/deploymenttarget"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/data/ent/targetconfiguration"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeploymentJobUpdate is the builder for updating DeploymentJob entities.
type DeploymentJobUpdate struct {
	config
	hooks     []Hook
	mutation  *DeploymentJobMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeploymentJobUpdate builder.
func (_u *DeploymentJobUpdate) Where(ps ...predicate.DeploymentJob) *DeploymentJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *DeploymentJobUpdate) SetCreateBy(v uint32) *DeploymentJobUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableCreateBy(v *uint32) *DeploymentJobUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *DeploymentJobUpdate) AddCreateBy(v int32) *DeploymentJobUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *DeploymentJobUpdate) ClearCreateBy() *DeploymentJobUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DeploymentJobUpdate) SetUpdateTime(v time.Time) *DeploymentJobUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableUpdateTime(v *time.Time) *DeploymentJobUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DeploymentJobUpdate) ClearUpdateTime() *DeploymentJobUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DeploymentJobUpdate) SetDeleteTime(v time.Time) *DeploymentJobUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableDeleteTime(v *time.Time) *DeploymentJobUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DeploymentJobUpdate) ClearDeleteTime() *DeploymentJobUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeploymentTargetID sets the "deployment_target_id" field.
func (_u *DeploymentJobUpdate) SetDeploymentTargetID(v string) *DeploymentJobUpdate {
	_u.mutation.SetDeploymentTargetID(v)
	return _u
}

// SetNillableDeploymentTargetID sets the "deployment_target_id" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableDeploymentTargetID(v *string) *DeploymentJobUpdate {
	if v != nil {
		_u.SetDeploymentTargetID(*v)
	}
	return _u
}

// ClearDeploymentTargetID clears the value of the "deployment_target_id" field.
func (_u *DeploymentJobUpdate) ClearDeploymentTargetID() *DeploymentJobUpdate {
	_u.mutation.ClearDeploymentTargetID()
	return _u
}

// SetTargetConfigurationID sets the "target_configuration_id" field.
func (_u *DeploymentJobUpdate) SetTargetConfigurationID(v string) *DeploymentJobUpdate {
	_u.mutation.SetTargetConfigurationID(v)
	return _u
}

// SetNillableTargetConfigurationID sets the "target_configuration_id" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableTargetConfigurationID(v *string) *DeploymentJobUpdate {
	if v != nil {
		_u.SetTargetConfigurationID(*v)
	}
	return _u
}

// ClearTargetConfigurationID clears the value of the "target_configuration_id" field.
func (_u *DeploymentJobUpdate) ClearTargetConfigurationID() *DeploymentJobUpdate {
	_u.mutation.ClearTargetConfigurationID()
	return _u
}

// SetParentJobID sets the "parent_job_id" field.
func (_u *DeploymentJobUpdate) SetParentJobID(v string) *DeploymentJobUpdate {
	_u.mutation.SetParentJobID(v)
	return _u
}

// SetNillableParentJobID sets the "parent_job_id" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableParentJobID(v *string) *DeploymentJobUpdate {
	if v != nil {
		_u.SetParentJobID(*v)
	}
	return _u
}

// ClearParentJobID clears the value of the "parent_job_id" field.
func (_u *DeploymentJobUpdate) ClearParentJobID() *DeploymentJobUpdate {
	_u.mutation.ClearParentJobID()
	return _u
}

// SetCertificateID sets the "certificate_id" field.
func (_u *DeploymentJobUpdate) SetCertificateID(v string) *DeploymentJobUpdate {
	_u.mutation.SetCertificateID(v)
	return _u
}

// SetNillableCertificateID sets the "certificate_id" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableCertificateID(v *string) *DeploymentJobUpdate {
	if v != nil {
		_u.SetCertificateID(*v)
	}
	return _u
}

// SetCertificateSerial sets the "certificate_serial" field.
func (_u *DeploymentJobUpdate) SetCertificateSerial(v string) *DeploymentJobUpdate {
	_u.mutation.SetCertificateSerial(v)
	return _u
}

// SetNillableCertificateSerial sets the "certificate_serial" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableCertificateSerial(v *string) *DeploymentJobUpdate {
	if v != nil {
		_u.SetCertificateSerial(*v)
	}
	return _u
}

// ClearCertificateSerial clears the value of the "certificate_serial" field.
func (_u *DeploymentJobUpdate) ClearCertificateSerial() *DeploymentJobUpdate {
	_u.mutation.ClearCertificateSerial()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeploymentJobUpdate) SetStatus(v deploymentjob.Status) *DeploymentJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableStatus(v *deploymentjob.Status) *DeploymentJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusMessage sets the "status_message" field.
func (_u *DeploymentJobUpdate) SetStatusMessage(v string) *DeploymentJobUpdate {
	_u.mutation.SetStatusMessage(v)
	return _u
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableStatusMessage(v *string) *DeploymentJobUpdate {
	if v != nil {
		_u.SetStatusMessage(*v)
	}
	return _u
}

// ClearStatusMessage clears the value of the "status_message" field.
func (_u *DeploymentJobUpdate) ClearStatusMessage() *DeploymentJobUpdate {
	_u.mutation.ClearStatusMessage()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *DeploymentJobUpdate) SetProgress(v int32) *DeploymentJobUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableProgress(v *int32) *DeploymentJobUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *DeploymentJobUpdate) AddProgress(v int32) *DeploymentJobUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *DeploymentJobUpdate) SetRetryCount(v int32) *DeploymentJobUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableRetryCount(v *int32) *DeploymentJobUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *DeploymentJobUpdate) AddRetryCount(v int32) *DeploymentJobUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *DeploymentJobUpdate) SetMaxRetries(v int32) *DeploymentJobUpdate {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableMaxRetries(v *int32) *DeploymentJobUpdate {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *DeploymentJobUpdate) AddMaxRetries(v int32) *DeploymentJobUpdate {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *DeploymentJobUpdate) SetTriggeredBy(v deploymentjob.TriggeredBy) *DeploymentJobUpdate {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableTriggeredBy(v *deploymentjob.TriggeredBy) *DeploymentJobUpdate {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *DeploymentJobUpdate) SetResult(v map[string]interface{}) *DeploymentJobUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *DeploymentJobUpdate) ClearResult() *DeploymentJobUpdate {
	_u.mutation.ClearResult()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DeploymentJobUpdate) SetStartedAt(v time.Time) *DeploymentJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableStartedAt(v *time.Time) *DeploymentJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DeploymentJobUpdate) ClearStartedAt() *DeploymentJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DeploymentJobUpdate) SetCompletedAt(v time.Time) *DeploymentJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableCompletedAt(v *time.Time) *DeploymentJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DeploymentJobUpdate) ClearCompletedAt() *DeploymentJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *DeploymentJobUpdate) SetNextRetryAt(v time.Time) *DeploymentJobUpdate {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *DeploymentJobUpdate) SetNillableNextRetryAt(v *time.Time) *DeploymentJobUpdate {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *DeploymentJobUpdate) ClearNextRetryAt() *DeploymentJobUpdate {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// SetDeploymentTarget sets the "deployment_target" edge to the DeploymentTarget entity.
func (_u *DeploymentJobUpdate) SetDeploymentTarget(v *DeploymentTarget) *DeploymentJobUpdate {
	return _u.SetDeploymentTargetID(v.ID)
}

// SetTargetConfiguration sets the "target_configuration" edge to the TargetConfiguration entity.
func (_u *DeploymentJobUpdate) SetTargetConfiguration(v *TargetConfiguration) *DeploymentJobUpdate {
	return _u.SetTargetConfigurationID(v.ID)
}

// SetParentJob sets the "parent_job" edge to the DeploymentJob entity.
func (_u *DeploymentJobUpdate) SetParentJob(v *DeploymentJob) *DeploymentJobUpdate {
	return _u.SetParentJobID(v.ID)
}

// AddChildJobIDs adds the "child_jobs" edge to the DeploymentJob entity by IDs.
func (_u *DeploymentJobUpdate) AddChildJobIDs(ids ...string) *DeploymentJobUpdate {
	_u.mutation.AddChildJobIDs(ids...)
	return _u
}

// AddChildJobs adds the "child_jobs" edges to the DeploymentJob entity.
func (_u *DeploymentJobUpdate) AddChildJobs(v ...*DeploymentJob) *DeploymentJobUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildJobIDs(ids...)
}

// AddHistoryIDs adds the "history" edge to the DeploymentHistory entity by IDs.
func (_u *DeploymentJobUpdate) AddHistoryIDs(ids ...uint32) *DeploymentJobUpdate {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistory adds the "history" edges to the DeploymentHistory entity.
func (_u *DeploymentJobUpdate) AddHistory(v ...*DeploymentHistory) *DeploymentJobUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// Mutation returns the DeploymentJobMutation object of the builder.
func (_u *DeploymentJobUpdate) Mutation() *DeploymentJobMutation {
	return _u.mutation
}

// ClearDeploymentTarget clears the "deployment_target" edge to the DeploymentTarget entity.
func (_u *DeploymentJobUpdate) ClearDeploymentTarget() *DeploymentJobUpdate {
	_u.mutation.ClearDeploymentTarget()
	return _u
}

// ClearTargetConfiguration clears the "target_configuration" edge to the TargetConfiguration entity.
func (_u *DeploymentJobUpdate) ClearTargetConfiguration() *DeploymentJobUpdate {
	_u.mutation.ClearTargetConfiguration()
	return _u
}

// ClearParentJob clears the "parent_job" edge to the DeploymentJob entity.
func (_u *DeploymentJobUpdate) ClearParentJob() *DeploymentJobUpdate {
	_u.mutation.ClearParentJob()
	return _u
}

// ClearChildJobs clears all "child_jobs" edges to the DeploymentJob entity.
func (_u *DeploymentJobUpdate) ClearChildJobs() *DeploymentJobUpdate {
	_u.mutation.ClearChildJobs()
	return _u
}

// RemoveChildJobIDs removes the "child_jobs" edge to DeploymentJob entities by IDs.
func (_u *DeploymentJobUpdate) RemoveChildJobIDs(ids ...string) *DeploymentJobUpdate {
	_u.mutation.RemoveChildJobIDs(ids...)
	return _u
}

// RemoveChildJobs removes "child_jobs" edges to DeploymentJob entities.
func (_u *DeploymentJobUpdate) RemoveChildJobs(v ...*DeploymentJob) *DeploymentJobUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildJobIDs(ids...)
}

// ClearHistory clears all "history" edges to the DeploymentHistory entity.
func (_u *DeploymentJobUpdate) ClearHistory() *DeploymentJobUpdate {
	_u.mutation.ClearHistory()
	return _u
}

// RemoveHistoryIDs removes the "history" edge to DeploymentHistory entities by IDs.
func (_u *DeploymentJobUpdate) RemoveHistoryIDs(ids ...uint32) *DeploymentJobUpdate {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistory removes "history" edges to DeploymentHistory entities.
func (_u *DeploymentJobUpdate) RemoveHistory(v ...*DeploymentHistory) *DeploymentJobUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeploymentJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeploymentJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentJobUpdate) check() error {
	if v, ok := _u.mutation.CertificateID(); ok {
		if err := deploymentjob.CertificateIDValidator(v); err != nil {
			return &ValidationError{Name: "certificate_id", err: fmt.Errorf(`ent: validator failed for field "DeploymentJob.certificate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deploymentjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DeploymentJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggeredBy(); ok {
		if err := deploymentjob.TriggeredByValidator(v); err != nil {
			return &ValidationError{Name: "triggered_by", err: fmt.Errorf(`ent: validator failed for field "DeploymentJob.triggered_by": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeploymentJobUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeploymentJobUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeploymentJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploymentjob.Table, deploymentjob.Columns, sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(deploymentjob.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(deploymentjob.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(deploymentjob.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(deploymentjob.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(deploymentjob.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(deploymentjob.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(deploymentjob.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(deploymentjob.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(deploymentjob.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.CertificateID(); ok {
		_spec.SetField(deploymentjob.FieldCertificateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertificateSerial(); ok {
		_spec.SetField(deploymentjob.FieldCertificateSerial, field.TypeString, value)
	}
	if _u.mutation.CertificateSerialCleared() {
		_spec.ClearField(deploymentjob.FieldCertificateSerial, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deploymentjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusMessage(); ok {
		_spec.SetField(deploymentjob.FieldStatusMessage, field.TypeString, value)
	}
	if _u.mutation.StatusMessageCleared() {
		_spec.ClearField(deploymentjob.FieldStatusMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(deploymentjob.FieldProgress, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(deploymentjob.FieldProgress, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(deploymentjob.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(deploymentjob.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(deploymentjob.FieldMaxRetries, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(deploymentjob.FieldMaxRetries, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(deploymentjob.FieldTriggeredBy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(deploymentjob.FieldResult, field.TypeJSON, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(deploymentjob.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(deploymentjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(deploymentjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(deploymentjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(deploymentjob.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(deploymentjob.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(deploymentjob.FieldNextRetryAt, field.TypeTime)
	}
	if _u.mutation.DeploymentTargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.DeploymentTargetTable,
			Columns: []string{deploymentjob.DeploymentTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenttarget.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeploymentTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.DeploymentTargetTable,
			Columns: []string{deploymentjob.DeploymentTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenttarget.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetConfigurationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.TargetConfigurationTable,
			Columns: []string{deploymentjob.TargetConfigurationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(targetconfiguration.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetConfigurationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.TargetConfigurationTable,
			Columns: []string{deploymentjob.TargetConfigurationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(targetconfiguration.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentJobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.ParentJobTable,
			Columns: []string{deploymentjob.ParentJobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentJobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.ParentJobTable,
			Columns: []string{deploymentjob.ParentJobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.ChildJobsTable,
			Columns: []string{deploymentjob.ChildJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildJobsIDs(); len(nodes) > 0 && !_u.mutation.ChildJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.ChildJobsTable,
			Columns: []string{deploymentjob.ChildJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.ChildJobsTable,
			Columns: []string{deploymentjob.ChildJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.HistoryTable,
			Columns: []string{deploymentjob.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenthistory.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoryIDs(); len(nodes) > 0 && !_u.mutation.HistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.HistoryTable,
			Columns: []string{deploymentjob.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenthistory.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.HistoryTable,
			Columns: []string{deploymentjob.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenthistory.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploymentjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeploymentJobUpdateOne is the builder for updating a single DeploymentJob entity.
type DeploymentJobUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeploymentJobMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *DeploymentJobUpdateOne) SetCreateBy(v uint32) *DeploymentJobUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableCreateBy(v *uint32) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *DeploymentJobUpdateOne) AddCreateBy(v int32) *DeploymentJobUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *DeploymentJobUpdateOne) ClearCreateBy() *DeploymentJobUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DeploymentJobUpdateOne) SetUpdateTime(v time.Time) *DeploymentJobUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableUpdateTime(v *time.Time) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DeploymentJobUpdateOne) ClearUpdateTime() *DeploymentJobUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DeploymentJobUpdateOne) SetDeleteTime(v time.Time) *DeploymentJobUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableDeleteTime(v *time.Time) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DeploymentJobUpdateOne) ClearDeleteTime() *DeploymentJobUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeploymentTargetID sets the "deployment_target_id" field.
func (_u *DeploymentJobUpdateOne) SetDeploymentTargetID(v string) *DeploymentJobUpdateOne {
	_u.mutation.SetDeploymentTargetID(v)
	return _u
}

// SetNillableDeploymentTargetID sets the "deployment_target_id" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableDeploymentTargetID(v *string) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetDeploymentTargetID(*v)
	}
	return _u
}

// ClearDeploymentTargetID clears the value of the "deployment_target_id" field.
func (_u *DeploymentJobUpdateOne) ClearDeploymentTargetID() *DeploymentJobUpdateOne {
	_u.mutation.ClearDeploymentTargetID()
	return _u
}

// SetTargetConfigurationID sets the "target_configuration_id" field.
func (_u *DeploymentJobUpdateOne) SetTargetConfigurationID(v string) *DeploymentJobUpdateOne {
	_u.mutation.SetTargetConfigurationID(v)
	return _u
}

// SetNillableTargetConfigurationID sets the "target_configuration_id" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableTargetConfigurationID(v *string) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetTargetConfigurationID(*v)
	}
	return _u
}

// ClearTargetConfigurationID clears the value of the "target_configuration_id" field.
func (_u *DeploymentJobUpdateOne) ClearTargetConfigurationID() *DeploymentJobUpdateOne {
	_u.mutation.ClearTargetConfigurationID()
	return _u
}

// SetParentJobID sets the "parent_job_id" field.
func (_u *DeploymentJobUpdateOne) SetParentJobID(v string) *DeploymentJobUpdateOne {
	_u.mutation.SetParentJobID(v)
	return _u
}

// SetNillableParentJobID sets the "parent_job_id" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableParentJobID(v *string) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetParentJobID(*v)
	}
	return _u
}

// ClearParentJobID clears the value of the "parent_job_id" field.
func (_u *DeploymentJobUpdateOne) ClearParentJobID() *DeploymentJobUpdateOne {
	_u.mutation.ClearParentJobID()
	return _u
}

// SetCertificateID sets the "certificate_id" field.
func (_u *DeploymentJobUpdateOne) SetCertificateID(v string) *DeploymentJobUpdateOne {
	_u.mutation.SetCertificateID(v)
	return _u
}

// SetNillableCertificateID sets the "certificate_id" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableCertificateID(v *string) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetCertificateID(*v)
	}
	return _u
}

// SetCertificateSerial sets the "certificate_serial" field.
func (_u *DeploymentJobUpdateOne) SetCertificateSerial(v string) *DeploymentJobUpdateOne {
	_u.mutation.SetCertificateSerial(v)
	return _u
}

// SetNillableCertificateSerial sets the "certificate_serial" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableCertificateSerial(v *string) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetCertificateSerial(*v)
	}
	return _u
}

// ClearCertificateSerial clears the value of the "certificate_serial" field.
func (_u *DeploymentJobUpdateOne) ClearCertificateSerial() *DeploymentJobUpdateOne {
	_u.mutation.ClearCertificateSerial()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeploymentJobUpdateOne) SetStatus(v deploymentjob.Status) *DeploymentJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableStatus(v *deploymentjob.Status) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusMessage sets the "status_message" field.
func (_u *DeploymentJobUpdateOne) SetStatusMessage(v string) *DeploymentJobUpdateOne {
	_u.mutation.SetStatusMessage(v)
	return _u
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableStatusMessage(v *string) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetStatusMessage(*v)
	}
	return _u
}

// ClearStatusMessage clears the value of the "status_message" field.
func (_u *DeploymentJobUpdateOne) ClearStatusMessage() *DeploymentJobUpdateOne {
	_u.mutation.ClearStatusMessage()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *DeploymentJobUpdateOne) SetProgress(v int32) *DeploymentJobUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableProgress(v *int32) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *DeploymentJobUpdateOne) AddProgress(v int32) *DeploymentJobUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *DeploymentJobUpdateOne) SetRetryCount(v int32) *DeploymentJobUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableRetryCount(v *int32) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *DeploymentJobUpdateOne) AddRetryCount(v int32) *DeploymentJobUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *DeploymentJobUpdateOne) SetMaxRetries(v int32) *DeploymentJobUpdateOne {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableMaxRetries(v *int32) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *DeploymentJobUpdateOne) AddMaxRetries(v int32) *DeploymentJobUpdateOne {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *DeploymentJobUpdateOne) SetTriggeredBy(v deploymentjob.TriggeredBy) *DeploymentJobUpdateOne {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableTriggeredBy(v *deploymentjob.TriggeredBy) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *DeploymentJobUpdateOne) SetResult(v map[string]interface{}) *DeploymentJobUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *DeploymentJobUpdateOne) ClearResult() *DeploymentJobUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DeploymentJobUpdateOne) SetStartedAt(v time.Time) *DeploymentJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableStartedAt(v *time.Time) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DeploymentJobUpdateOne) ClearStartedAt() *DeploymentJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DeploymentJobUpdateOne) SetCompletedAt(v time.Time) *DeploymentJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableCompletedAt(v *time.Time) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DeploymentJobUpdateOne) ClearCompletedAt() *DeploymentJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *DeploymentJobUpdateOne) SetNextRetryAt(v time.Time) *DeploymentJobUpdateOne {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *DeploymentJobUpdateOne) SetNillableNextRetryAt(v *time.Time) *DeploymentJobUpdateOne {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *DeploymentJobUpdateOne) ClearNextRetryAt() *DeploymentJobUpdateOne {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// SetDeploymentTarget sets the "deployment_target" edge to the DeploymentTarget entity.
func (_u *DeploymentJobUpdateOne) SetDeploymentTarget(v *DeploymentTarget) *DeploymentJobUpdateOne {
	return _u.SetDeploymentTargetID(v.ID)
}

// SetTargetConfiguration sets the "target_configuration" edge to the TargetConfiguration entity.
func (_u *DeploymentJobUpdateOne) SetTargetConfiguration(v *TargetConfiguration) *DeploymentJobUpdateOne {
	return _u.SetTargetConfigurationID(v.ID)
}

// SetParentJob sets the "parent_job" edge to the DeploymentJob entity.
func (_u *DeploymentJobUpdateOne) SetParentJob(v *DeploymentJob) *DeploymentJobUpdateOne {
	return _u.SetParentJobID(v.ID)
}

// AddChildJobIDs adds the "child_jobs" edge to the DeploymentJob entity by IDs.
func (_u *DeploymentJobUpdateOne) AddChildJobIDs(ids ...string) *DeploymentJobUpdateOne {
	_u.mutation.AddChildJobIDs(ids...)
	return _u
}

// AddChildJobs adds the "child_jobs" edges to the DeploymentJob entity.
func (_u *DeploymentJobUpdateOne) AddChildJobs(v ...*DeploymentJob) *DeploymentJobUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildJobIDs(ids...)
}

// AddHistoryIDs adds the "history" edge to the DeploymentHistory entity by IDs.
func (_u *DeploymentJobUpdateOne) AddHistoryIDs(ids ...uint32) *DeploymentJobUpdateOne {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistory adds the "history" edges to the DeploymentHistory entity.
func (_u *DeploymentJobUpdateOne) AddHistory(v ...*DeploymentHistory) *DeploymentJobUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// Mutation returns the DeploymentJobMutation object of the builder.
func (_u *DeploymentJobUpdateOne) Mutation() *DeploymentJobMutation {
	return _u.mutation
}

// ClearDeploymentTarget clears the "deployment_target" edge to the DeploymentTarget entity.
func (_u *DeploymentJobUpdateOne) ClearDeploymentTarget() *DeploymentJobUpdateOne {
	_u.mutation.ClearDeploymentTarget()
	return _u
}

// ClearTargetConfiguration clears the "target_configuration" edge to the TargetConfiguration entity.
func (_u *DeploymentJobUpdateOne) ClearTargetConfiguration() *DeploymentJobUpdateOne {
	_u.mutation.ClearTargetConfiguration()
	return _u
}

// ClearParentJob clears the "parent_job" edge to the DeploymentJob entity.
func (_u *DeploymentJobUpdateOne) ClearParentJob() *DeploymentJobUpdateOne {
	_u.mutation.ClearParentJob()
	return _u
}

// ClearChildJobs clears all "child_jobs" edges to the DeploymentJob entity.
func (_u *DeploymentJobUpdateOne) ClearChildJobs() *DeploymentJobUpdateOne {
	_u.mutation.ClearChildJobs()
	return _u
}

// RemoveChildJobIDs removes the "child_jobs" edge to DeploymentJob entities by IDs.
func (_u *DeploymentJobUpdateOne) RemoveChildJobIDs(ids ...string) *DeploymentJobUpdateOne {
	_u.mutation.RemoveChildJobIDs(ids...)
	return _u
}

// RemoveChildJobs removes "child_jobs" edges to DeploymentJob entities.
func (_u *DeploymentJobUpdateOne) RemoveChildJobs(v ...*DeploymentJob) *DeploymentJobUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildJobIDs(ids...)
}

// ClearHistory clears all "history" edges to the DeploymentHistory entity.
func (_u *DeploymentJobUpdateOne) ClearHistory() *DeploymentJobUpdateOne {
	_u.mutation.ClearHistory()
	return _u
}

// RemoveHistoryIDs removes the "history" edge to DeploymentHistory entities by IDs.
func (_u *DeploymentJobUpdateOne) RemoveHistoryIDs(ids ...uint32) *DeploymentJobUpdateOne {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistory removes "history" edges to DeploymentHistory entities.
func (_u *DeploymentJobUpdateOne) RemoveHistory(v ...*DeploymentHistory) *DeploymentJobUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// Where appends a list predicates to the DeploymentJobUpdate builder.
func (_u *DeploymentJobUpdateOne) Where(ps ...predicate.DeploymentJob) *DeploymentJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeploymentJobUpdateOne) Select(field string, fields ...string) *DeploymentJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeploymentJob entity.
func (_u *DeploymentJobUpdateOne) Save(ctx context.Context) (*DeploymentJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentJobUpdateOne) SaveX(ctx context.Context) *DeploymentJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeploymentJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentJobUpdateOne) check() error {
	if v, ok := _u.mutation.CertificateID(); ok {
		if err := deploymentjob.CertificateIDValidator(v); err != nil {
			return &ValidationError{Name: "certificate_id", err: fmt.Errorf(`ent: validator failed for field "DeploymentJob.certificate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deploymentjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DeploymentJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggeredBy(); ok {
		if err := deploymentjob.TriggeredByValidator(v); err != nil {
			return &ValidationError{Name: "triggered_by", err: fmt.Errorf(`ent: validator failed for field "DeploymentJob.triggered_by": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeploymentJobUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeploymentJobUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeploymentJobUpdateOne) sqlSave(ctx context.Context) (_node *DeploymentJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploymentjob.Table, deploymentjob.Columns, sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeploymentJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploymentjob.FieldID)
		for _, f := range fields {
			if !deploymentjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deploymentjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(deploymentjob.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(deploymentjob.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(deploymentjob.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(deploymentjob.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(deploymentjob.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(deploymentjob.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(deploymentjob.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(deploymentjob.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(deploymentjob.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.CertificateID(); ok {
		_spec.SetField(deploymentjob.FieldCertificateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CertificateSerial(); ok {
		_spec.SetField(deploymentjob.FieldCertificateSerial, field.TypeString, value)
	}
	if _u.mutation.CertificateSerialCleared() {
		_spec.ClearField(deploymentjob.FieldCertificateSerial, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deploymentjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StatusMessage(); ok {
		_spec.SetField(deploymentjob.FieldStatusMessage, field.TypeString, value)
	}
	if _u.mutation.StatusMessageCleared() {
		_spec.ClearField(deploymentjob.FieldStatusMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(deploymentjob.FieldProgress, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(deploymentjob.FieldProgress, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(deploymentjob.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(deploymentjob.FieldRetryCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(deploymentjob.FieldMaxRetries, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(deploymentjob.FieldMaxRetries, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(deploymentjob.FieldTriggeredBy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(deploymentjob.FieldResult, field.TypeJSON, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(deploymentjob.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(deploymentjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(deploymentjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(deploymentjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(deploymentjob.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(deploymentjob.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(deploymentjob.FieldNextRetryAt, field.TypeTime)
	}
	if _u.mutation.DeploymentTargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.DeploymentTargetTable,
			Columns: []string{deploymentjob.DeploymentTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenttarget.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeploymentTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.DeploymentTargetTable,
			Columns: []string{deploymentjob.DeploymentTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenttarget.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetConfigurationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.TargetConfigurationTable,
			Columns: []string{deploymentjob.TargetConfigurationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(targetconfiguration.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetConfigurationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.TargetConfigurationTable,
			Columns: []string{deploymentjob.TargetConfigurationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(targetconfiguration.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentJobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.ParentJobTable,
			Columns: []string{deploymentjob.ParentJobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentJobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploymentjob.ParentJobTable,
			Columns: []string{deploymentjob.ParentJobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.ChildJobsTable,
			Columns: []string{deploymentjob.ChildJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildJobsIDs(); len(nodes) > 0 && !_u.mutation.ChildJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.ChildJobsTable,
			Columns: []string{deploymentjob.ChildJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.ChildJobsTable,
			Columns: []string{deploymentjob.ChildJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.HistoryTable,
			Columns: []string{deploymentjob.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenthistory.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoryIDs(); len(nodes) > 0 && !_u.mutation.HistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.HistoryTable,
			Columns: []string{deploymentjob.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenthistory.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentjob.HistoryTable,
			Columns: []string{deploymentjob.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymenthistory.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DeploymentJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploymentjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
