CREATE DATABASE openfga;
CREATE DATABASE auth;
CREATE DATABASE lcm;
\c auth
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE ROLE auth_app LOGIN PASSWORD 'dev' NOBYPASSRLS;
GRANT CONNECT ON DATABASE auth TO auth_app;
\c lcm
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE ROLE lcm_app LOGIN PASSWORD 'dev' NOBYPASSRLS;
GRANT CONNECT ON DATABASE lcm TO lcm_app;
\c gateway
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE ROLE gateway_app LOGIN PASSWORD 'dev' NOBYPASSRLS;
GRANT CONNECT ON DATABASE gateway TO gateway_app;
