// Code generated by ent, DO NOT EDIT.

package deploymentjob

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the deploymentjob type in the database.
	Label = "deployment_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDeploymentTargetID holds the string denoting the deployment_target_id field in the database.
	FieldDeploymentTargetID = "deployment_target_id"
	// FieldTargetConfigurationID holds the string denoting the target_configuration_id field in the database.
	FieldTargetConfigurationID = "target_configuration_id"
	// FieldParentJobID holds the string denoting the parent_job_id field in the database.
	FieldParentJobID = "parent_job_id"
	// FieldCertificateID holds the string denoting the certificate_id field in the database.
	FieldCertificateID = "certificate_id"
	// FieldCertificateSerial holds the string denoting the certificate_serial field in the database.
	FieldCertificateSerial = "certificate_serial"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusMessage holds the string denoting the status_message field in the database.
	FieldStatusMessage = "status_message"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldMaxRetries holds the string denoting the max_retries field in the database.
	FieldMaxRetries = "max_retries"
	// FieldTriggeredBy holds the string denoting the triggered_by field in the database.
	FieldTriggeredBy = "triggered_by"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldNextRetryAt holds the string denoting the next_retry_at field in the database.
	FieldNextRetryAt = "next_retry_at"
	// EdgeDeploymentTarget holds the string denoting the deployment_target edge name in mutations.
	EdgeDeploymentTarget = "deployment_target"
	// EdgeTargetConfiguration holds the string denoting the target_configuration edge name in mutations.
	EdgeTargetConfiguration = "target_configuration"
	// EdgeParentJob holds the string denoting the parent_job edge name in mutations.
	EdgeParentJob = "parent_job"
	// EdgeChildJobs holds the string denoting the child_jobs edge name in mutations.
	EdgeChildJobs = "child_jobs"
	// EdgeHistory holds the string denoting the history edge name in mutations.
	EdgeHistory = "history"
	// Table holds the table name of the deploymentjob in the database.
	Table = "deployer_jobs"
	// DeploymentTargetTable is the table that holds the deployment_target relation/edge.
	DeploymentTargetTable = "deployer_jobs"
	// DeploymentTargetInverseTable is the table name for the DeploymentTarget entity.
	// It exists in this package in order to avoid circular dependency with the "deploymenttarget" package.
	DeploymentTargetInverseTable = "deployer_targets"
	// DeploymentTargetColumn is the table column denoting the deployment_target relation/edge.
	DeploymentTargetColumn = "deployment_target_id"
	// TargetConfigurationTable is the table that holds the target_configuration relation/edge.
	TargetConfigurationTable = "deployer_jobs"
	// TargetConfigurationInverseTable is the table name for the TargetConfiguration entity.
	// It exists in this package in order to avoid circular dependency with the "targetconfiguration" package.
	TargetConfigurationInverseTable = "deployer_target_configs"
	// TargetConfigurationColumn is the table column denoting the target_configuration relation/edge.
	TargetConfigurationColumn = "target_configuration_id"
	// ParentJobTable is the table that holds the parent_job relation/edge.
	ParentJobTable = "deployer_jobs"
	// ParentJobColumn is the table column denoting the parent_job relation/edge.
	ParentJobColumn = "parent_job_id"
	// ChildJobsTable is the table that holds the child_jobs relation/edge.
	ChildJobsTable = "deployer_jobs"
	// ChildJobsColumn is the table column denoting the child_jobs relation/edge.
	ChildJobsColumn = "parent_job_id"
	// HistoryTable is the table that holds the history relation/edge.
	HistoryTable = "deployer_history"
	// HistoryInverseTable is the table name for the DeploymentHistory entity.
	// It exists in this package in order to avoid circular dependency with the "deploymenthistory" package.
	HistoryInverseTable = "deployer_history"
	// HistoryColumn is the table column denoting the history relation/edge.
	HistoryColumn = "job_id"
)

// Columns holds all SQL columns for deploymentjob fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldDeploymentTargetID,
	FieldTargetConfigurationID,
	FieldParentJobID,
	FieldCertificateID,
	FieldCertificateSerial,
	FieldStatus,
	FieldStatusMessage,
	FieldProgress,
	FieldRetryCount,
	FieldMaxRetries,
	FieldTriggeredBy,
	FieldResult,
	FieldStartedAt,
	FieldCompletedAt,
	FieldNextRetryAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// CertificateIDValidator is a validator for the "certificate_id" field. It is called by the builders before save.
	CertificateIDValidator func(string) error
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress int32
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int32
	// DefaultMaxRetries holds the default value on creation for the "max_retries" field.
	DefaultMaxRetries int32
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusJOB_STATUS_PENDING is the default value of the Status enum.
const DefaultStatus = StatusJOB_STATUS_PENDING

// Status values.
const (
	StatusJOB_STATUS_UNSPECIFIED Status = "JOB_STATUS_UNSPECIFIED"
	StatusJOB_STATUS_PENDING     Status = "JOB_STATUS_PENDING"
	StatusJOB_STATUS_PROCESSING  Status = "JOB_STATUS_PROCESSING"
	StatusJOB_STATUS_COMPLETED   Status = "JOB_STATUS_COMPLETED"
	StatusJOB_STATUS_FAILED      Status = "JOB_STATUS_FAILED"
	StatusJOB_STATUS_CANCELLED   Status = "JOB_STATUS_CANCELLED"
	StatusJOB_STATUS_RETRYING    Status = "JOB_STATUS_RETRYING"
	StatusJOB_STATUS_PARTIAL     Status = "JOB_STATUS_PARTIAL"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusJOB_STATUS_UNSPECIFIED, StatusJOB_STATUS_PENDING, StatusJOB_STATUS_PROCESSING, StatusJOB_STATUS_COMPLETED, StatusJOB_STATUS_FAILED, StatusJOB_STATUS_CANCELLED, StatusJOB_STATUS_RETRYING, StatusJOB_STATUS_PARTIAL:
		return nil
	default:
		return fmt.Errorf("deploymentjob: invalid enum value for status field: %q", s)
	}
}

// TriggeredBy defines the type for the "triggered_by" enum field.
type TriggeredBy string

// TriggeredByTRIGGER_TYPE_MANUAL is the default value of the TriggeredBy enum.
const DefaultTriggeredBy = TriggeredByTRIGGER_TYPE_MANUAL

// TriggeredBy values.
const (
	TriggeredByTRIGGER_TYPE_UNSPECIFIED  TriggeredBy = "TRIGGER_TYPE_UNSPECIFIED"
	TriggeredByTRIGGER_TYPE_MANUAL       TriggeredBy = "TRIGGER_TYPE_MANUAL"
	TriggeredByTRIGGER_TYPE_EVENT        TriggeredBy = "TRIGGER_TYPE_EVENT"
	TriggeredByTRIGGER_TYPE_AUTO_RENEWAL TriggeredBy = "TRIGGER_TYPE_AUTO_RENEWAL"
)

func (tb TriggeredBy) String() string {
	return string(tb)
}

// TriggeredByValidator is a validator for the "triggered_by" field enum values. It is called by the builders before save.
func TriggeredByValidator(tb TriggeredBy) error {
	switch tb {
	case TriggeredByTRIGGER_TYPE_UNSPECIFIED, TriggeredByTRIGGER_TYPE_MANUAL, TriggeredByTRIGGER_TYPE_EVENT, TriggeredByTRIGGER_TYPE_AUTO_RENEWAL:
		return nil
	default:
		return fmt.Errorf("deploymentjob: invalid enum value for triggered_by field: %q", tb)
	}
}

// OrderOption defines the ordering options for the DeploymentJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDeploymentTargetID orders the results by the deployment_target_id field.
func ByDeploymentTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeploymentTargetID, opts...).ToFunc()
}

// ByTargetConfigurationID orders the results by the target_configuration_id field.
func ByTargetConfigurationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetConfigurationID, opts...).ToFunc()
}

// ByParentJobID orders the results by the parent_job_id field.
func ByParentJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentJobID, opts...).ToFunc()
}

// ByCertificateID orders the results by the certificate_id field.
func ByCertificateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertificateID, opts...).ToFunc()
}

// ByCertificateSerial orders the results by the certificate_serial field.
func ByCertificateSerial(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertificateSerial, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusMessage orders the results by the status_message field.
func ByStatusMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusMessage, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByMaxRetries orders the results by the max_retries field.
func ByMaxRetries(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRetries, opts...).ToFunc()
}

// ByTriggeredBy orders the results by the triggered_by field.
func ByTriggeredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredBy, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByNextRetryAt orders the results by the next_retry_at field.
func ByNextRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryAt, opts...).ToFunc()
}

// ByDeploymentTargetField orders the results by deployment_target field.
func ByDeploymentTargetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeploymentTargetStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetConfigurationField orders the results by target_configuration field.
func ByTargetConfigurationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetConfigurationStep(), sql.OrderByField(field, opts...))
	}
}

// ByParentJobField orders the results by parent_job field.
func ByParentJobField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentJobStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildJobsCount orders the results by child_jobs count.
func ByChildJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildJobsStep(), opts...)
	}
}

// ByChildJobs orders the results by child_jobs terms.
func ByChildJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHistoryCount orders the results by history count.
func ByHistoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHistoryStep(), opts...)
	}
}

// ByHistory orders the results by history terms.
func ByHistory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHistoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDeploymentTargetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeploymentTargetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeploymentTargetTable, DeploymentTargetColumn),
	)
}
func newTargetConfigurationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetConfigurationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetConfigurationTable, TargetConfigurationColumn),
	)
}
func newParentJobStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentJobTable, ParentJobColumn),
	)
}
func newChildJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildJobsTable, ChildJobsColumn),
	)
}
func newHistoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HistoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HistoryTable, HistoryColumn),
	)
}
