// Code generated by ent, DO NOT EDIT.

package ipscanjob

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ipscanjob type in the database.
	Label = "ip_scan_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldSubnetID holds the string denoting the subnet_id field in the database.
	FieldSubnetID = "subnet_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldStatusMessage holds the string denoting the status_message field in the database.
	FieldStatusMessage = "status_message"
	// FieldTotalAddresses holds the string denoting the total_addresses field in the database.
	FieldTotalAddresses = "total_addresses"
	// FieldScannedCount holds the string denoting the scanned_count field in the database.
	FieldScannedCount = "scanned_count"
	// FieldAliveCount holds the string denoting the alive_count field in the database.
	FieldAliveCount = "alive_count"
	// FieldNewCount holds the string denoting the new_count field in the database.
	FieldNewCount = "new_count"
	// FieldUpdatedCount holds the string denoting the updated_count field in the database.
	FieldUpdatedCount = "updated_count"
	// FieldTriggeredBy holds the string denoting the triggered_by field in the database.
	FieldTriggeredBy = "triggered_by"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldMaxRetries holds the string denoting the max_retries field in the database.
	FieldMaxRetries = "max_retries"
	// FieldNextRetryAt holds the string denoting the next_retry_at field in the database.
	FieldNextRetryAt = "next_retry_at"
	// FieldTimeoutMs holds the string denoting the timeout_ms field in the database.
	FieldTimeoutMs = "timeout_ms"
	// FieldConcurrency holds the string denoting the concurrency field in the database.
	FieldConcurrency = "concurrency"
	// FieldSkipReverseDNS holds the string denoting the skip_reverse_dns field in the database.
	FieldSkipReverseDNS = "skip_reverse_dns"
	// FieldTCPProbePorts holds the string denoting the tcp_probe_ports field in the database.
	FieldTCPProbePorts = "tcp_probe_ports"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// EdgeSubnet holds the string denoting the subnet edge name in mutations.
	EdgeSubnet = "subnet"
	// Table holds the table name of the ipscanjob in the database.
	Table = "ipam_ip_scan_jobs"
	// SubnetTable is the table that holds the subnet relation/edge.
	SubnetTable = "ipam_ip_scan_jobs"
	// SubnetInverseTable is the table name for the Subnet entity.
	// It exists in this package in order to avoid circular dependency with the "subnet" package.
	SubnetInverseTable = "ipam_subnets"
	// SubnetColumn is the table column denoting the subnet relation/edge.
	SubnetColumn = "subnet_id"
)

// Columns holds all SQL columns for ipscanjob fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldUpdateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldSubnetID,
	FieldStatus,
	FieldProgress,
	FieldStatusMessage,
	FieldTotalAddresses,
	FieldScannedCount,
	FieldAliveCount,
	FieldNewCount,
	FieldUpdatedCount,
	FieldTriggeredBy,
	FieldRetryCount,
	FieldMaxRetries,
	FieldNextRetryAt,
	FieldTimeoutMs,
	FieldConcurrency,
	FieldSkipReverseDNS,
	FieldTCPProbePorts,
	FieldStartedAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// SubnetIDValidator is a validator for the "subnet_id" field. It is called by the builders before save.
	SubnetIDValidator func(string) error
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress int32
	// DefaultTotalAddresses holds the default value on creation for the "total_addresses" field.
	DefaultTotalAddresses int64
	// DefaultScannedCount holds the default value on creation for the "scanned_count" field.
	DefaultScannedCount int64
	// DefaultAliveCount holds the default value on creation for the "alive_count" field.
	DefaultAliveCount int64
	// DefaultNewCount holds the default value on creation for the "new_count" field.
	DefaultNewCount int64
	// DefaultUpdatedCount holds the default value on creation for the "updated_count" field.
	DefaultUpdatedCount int64
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int32
	// DefaultMaxRetries holds the default value on creation for the "max_retries" field.
	DefaultMaxRetries int32
	// DefaultTimeoutMs holds the default value on creation for the "timeout_ms" field.
	DefaultTimeoutMs int32
	// DefaultConcurrency holds the default value on creation for the "concurrency" field.
	DefaultConcurrency int32
	// DefaultSkipReverseDNS holds the default value on creation for the "skip_reverse_dns" field.
	DefaultSkipReverseDNS bool
	// DefaultTCPProbePorts holds the default value on creation for the "tcp_probe_ports" field.
	DefaultTCPProbePorts string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING   Status = "PENDING"
	StatusSCANNING  Status = "SCANNING"
	StatusCOMPLETED Status = "COMPLETED"
	StatusFAILED    Status = "FAILED"
	StatusCANCELLED Status = "CANCELLED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusSCANNING, StatusCOMPLETED, StatusFAILED, StatusCANCELLED:
		return nil
	default:
		return fmt.Errorf("ipscanjob: invalid enum value for status field: %q", s)
	}
}

// TriggeredBy defines the type for the "triggered_by" enum field.
type TriggeredBy string

// TriggeredByMANUAL is the default value of the TriggeredBy enum.
const DefaultTriggeredBy = TriggeredByMANUAL

// TriggeredBy values.
const (
	TriggeredByAUTO   TriggeredBy = "AUTO"
	TriggeredByMANUAL TriggeredBy = "MANUAL"
)

func (tb TriggeredBy) String() string {
	return string(tb)
}

// TriggeredByValidator is a validator for the "triggered_by" field enum values. It is called by the builders before save.
func TriggeredByValidator(tb TriggeredBy) error {
	switch tb {
	case TriggeredByAUTO, TriggeredByMANUAL:
		return nil
	default:
		return fmt.Errorf("ipscanjob: invalid enum value for triggered_by field: %q", tb)
	}
}

// OrderOption defines the ordering options for the IpScanJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// BySubnetID orders the results by the subnet_id field.
func BySubnetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubnetID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByStatusMessage orders the results by the status_message field.
func ByStatusMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusMessage, opts...).ToFunc()
}

// ByTotalAddresses orders the results by the total_addresses field.
func ByTotalAddresses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAddresses, opts...).ToFunc()
}

// ByScannedCount orders the results by the scanned_count field.
func ByScannedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScannedCount, opts...).ToFunc()
}

// ByAliveCount orders the results by the alive_count field.
func ByAliveCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAliveCount, opts...).ToFunc()
}

// ByNewCount orders the results by the new_count field.
func ByNewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewCount, opts...).ToFunc()
}

// ByUpdatedCount orders the results by the updated_count field.
func ByUpdatedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedCount, opts...).ToFunc()
}

// ByTriggeredBy orders the results by the triggered_by field.
func ByTriggeredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredBy, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByMaxRetries orders the results by the max_retries field.
func ByMaxRetries(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRetries, opts...).ToFunc()
}

// ByNextRetryAt orders the results by the next_retry_at field.
func ByNextRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryAt, opts...).ToFunc()
}

// ByTimeoutMs orders the results by the timeout_ms field.
func ByTimeoutMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutMs, opts...).ToFunc()
}

// ByConcurrency orders the results by the concurrency field.
func ByConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrency, opts...).ToFunc()
}

// BySkipReverseDNS orders the results by the skip_reverse_dns field.
func BySkipReverseDNS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipReverseDNS, opts...).ToFunc()
}

// ByTCPProbePorts orders the results by the tcp_probe_ports field.
func ByTCPProbePorts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTCPProbePorts, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// BySubnetField orders the results by subnet field.
func BySubnetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubnetStep(), sql.OrderByField(field, opts...))
	}
}
func newSubnetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubnetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubnetTable, SubnetColumn),
	)
}
