// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/device"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/deviceinterface"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceInterfaceCreate is the builder for creating a DeviceInterface entity.
type DeviceInterfaceCreate struct {
	config
	mutation *DeviceInterfaceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *DeviceInterfaceCreate) SetCreateTime(v time.Time) *DeviceInterfaceCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableCreateTime(v *time.Time) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *DeviceInterfaceCreate) SetUpdateTime(v time.Time) *DeviceInterfaceCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableUpdateTime(v *time.Time) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *DeviceInterfaceCreate) SetDeleteTime(v time.Time) *DeviceInterfaceCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableDeleteTime(v *time.Time) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *DeviceInterfaceCreate) SetDeviceID(v string) *DeviceInterfaceCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DeviceInterfaceCreate) SetName(v string) *DeviceInterfaceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetMACAddress sets the "mac_address" field.
func (_c *DeviceInterfaceCreate) SetMACAddress(v string) *DeviceInterfaceCreate {
	_c.mutation.SetMACAddress(v)
	return _c
}

// SetNillableMACAddress sets the "mac_address" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableMACAddress(v *string) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetMACAddress(*v)
	}
	return _c
}

// SetInterfaceType sets the "interface_type" field.
func (_c *DeviceInterfaceCreate) SetInterfaceType(v string) *DeviceInterfaceCreate {
	_c.mutation.SetInterfaceType(v)
	return _c
}

// SetNillableInterfaceType sets the "interface_type" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableInterfaceType(v *string) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetInterfaceType(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *DeviceInterfaceCreate) SetEnabled(v bool) *DeviceInterfaceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableEnabled(v *bool) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSpeedMbps sets the "speed_mbps" field.
func (_c *DeviceInterfaceCreate) SetSpeedMbps(v int32) *DeviceInterfaceCreate {
	_c.mutation.SetSpeedMbps(v)
	return _c
}

// SetNillableSpeedMbps sets the "speed_mbps" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableSpeedMbps(v *int32) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetSpeedMbps(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *DeviceInterfaceCreate) SetDescription(v string) *DeviceInterfaceCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DeviceInterfaceCreate) SetNillableDescription(v *string) *DeviceInterfaceCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceInterfaceCreate) SetID(v string) *DeviceInterfaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDevice sets the "device" edge to the Device entity.
func (_c *DeviceInterfaceCreate) SetDevice(v *Device) *DeviceInterfaceCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the DeviceInterfaceMutation object of the builder.
func (_c *DeviceInterfaceCreate) Mutation() *DeviceInterfaceMutation {
	return _c.mutation
}

// Save creates the DeviceInterface in the database.
func (_c *DeviceInterfaceCreate) Save(ctx context.Context) (*DeviceInterface, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceInterfaceCreate) SaveX(ctx context.Context) *DeviceInterface {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceInterfaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceInterfaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceInterfaceCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := deviceinterface.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceInterfaceCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DeviceInterface.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := deviceinterface.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterface.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DeviceInterface.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := deviceinterface.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeviceInterface.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "DeviceInterface.enabled"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := deviceinterface.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterface.id": %w`, err)}
		}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "DeviceInterface.device"`)}
	}
	return nil
}

func (_c *DeviceInterfaceCreate) sqlSave(ctx context.Context) (*DeviceInterface, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DeviceInterface.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceInterfaceCreate) createSpec() (*DeviceInterface, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceInterface{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deviceinterface.Table, sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(deviceinterface.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(deviceinterface.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(deviceinterface.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(deviceinterface.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.MACAddress(); ok {
		_spec.SetField(deviceinterface.FieldMACAddress, field.TypeString, value)
		_node.MACAddress = value
	}
	if value, ok := _c.mutation.InterfaceType(); ok {
		_spec.SetField(deviceinterface.FieldInterfaceType, field.TypeString, value)
		_node.InterfaceType = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(deviceinterface.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SpeedMbps(); ok {
		_spec.SetField(deviceinterface.FieldSpeedMbps, field.TypeInt32, value)
		_node.SpeedMbps = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(deviceinterface.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterface.DeviceTable,
			Columns: []string{deviceinterface.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceInterface.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceInterfaceUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceInterfaceCreate) OnConflict(opts ...sql.ConflictOption) *DeviceInterfaceUpsertOne {
	_c.conflict = opts
	return &DeviceInterfaceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceInterface.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceInterfaceCreate) OnConflictColumns(columns ...string) *DeviceInterfaceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceInterfaceUpsertOne{
		create: _c,
	}
}

type (
	// DeviceInterfaceUpsertOne is the builder for "upsert"-ing
	//  one DeviceInterface node.
	DeviceInterfaceUpsertOne struct {
		create *DeviceInterfaceCreate
	}

	// DeviceInterfaceUpsert is the "OnConflict" setter.
	DeviceInterfaceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *DeviceInterfaceUpsert) SetUpdateTime(v time.Time) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateUpdateTime() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DeviceInterfaceUpsert) ClearUpdateTime() *DeviceInterfaceUpsert {
	u.SetNull(deviceinterface.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *DeviceInterfaceUpsert) SetDeleteTime(v time.Time) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateDeleteTime() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DeviceInterfaceUpsert) ClearDeleteTime() *DeviceInterfaceUpsert {
	u.SetNull(deviceinterface.FieldDeleteTime)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *DeviceInterfaceUpsert) SetDeviceID(v string) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateDeviceID() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldDeviceID)
	return u
}

// SetName sets the "name" field.
func (u *DeviceInterfaceUpsert) SetName(v string) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateName() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldName)
	return u
}

// SetMACAddress sets the "mac_address" field.
func (u *DeviceInterfaceUpsert) SetMACAddress(v string) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldMACAddress, v)
	return u
}

// UpdateMACAddress sets the "mac_address" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateMACAddress() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldMACAddress)
	return u
}

// ClearMACAddress clears the value of the "mac_address" field.
func (u *DeviceInterfaceUpsert) ClearMACAddress() *DeviceInterfaceUpsert {
	u.SetNull(deviceinterface.FieldMACAddress)
	return u
}

// SetInterfaceType sets the "interface_type" field.
func (u *DeviceInterfaceUpsert) SetInterfaceType(v string) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldInterfaceType, v)
	return u
}

// UpdateInterfaceType sets the "interface_type" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateInterfaceType() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldInterfaceType)
	return u
}

// ClearInterfaceType clears the value of the "interface_type" field.
func (u *DeviceInterfaceUpsert) ClearInterfaceType() *DeviceInterfaceUpsert {
	u.SetNull(deviceinterface.FieldInterfaceType)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *DeviceInterfaceUpsert) SetEnabled(v bool) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateEnabled() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldEnabled)
	return u
}

// SetSpeedMbps sets the "speed_mbps" field.
func (u *DeviceInterfaceUpsert) SetSpeedMbps(v int32) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldSpeedMbps, v)
	return u
}

// UpdateSpeedMbps sets the "speed_mbps" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateSpeedMbps() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldSpeedMbps)
	return u
}

// AddSpeedMbps adds v to the "speed_mbps" field.
func (u *DeviceInterfaceUpsert) AddSpeedMbps(v int32) *DeviceInterfaceUpsert {
	u.Add(deviceinterface.FieldSpeedMbps, v)
	return u
}

// ClearSpeedMbps clears the value of the "speed_mbps" field.
func (u *DeviceInterfaceUpsert) ClearSpeedMbps() *DeviceInterfaceUpsert {
	u.SetNull(deviceinterface.FieldSpeedMbps)
	return u
}

// SetDescription sets the "description" field.
func (u *DeviceInterfaceUpsert) SetDescription(v string) *DeviceInterfaceUpsert {
	u.Set(deviceinterface.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DeviceInterfaceUpsert) UpdateDescription() *DeviceInterfaceUpsert {
	u.SetExcluded(deviceinterface.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *DeviceInterfaceUpsert) ClearDescription() *DeviceInterfaceUpsert {
	u.SetNull(deviceinterface.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DeviceInterface.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deviceinterface.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceInterfaceUpsertOne) UpdateNewValues() *DeviceInterfaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(deviceinterface.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(deviceinterface.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceInterface.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceInterfaceUpsertOne) Ignore() *DeviceInterfaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceInterfaceUpsertOne) DoNothing() *DeviceInterfaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceInterfaceCreate.OnConflict
// documentation for more info.
func (u *DeviceInterfaceUpsertOne) Update(set func(*DeviceInterfaceUpsert)) *DeviceInterfaceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceInterfaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DeviceInterfaceUpsertOne) SetUpdateTime(v time.Time) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateUpdateTime() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DeviceInterfaceUpsertOne) ClearUpdateTime() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *DeviceInterfaceUpsertOne) SetDeleteTime(v time.Time) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateDeleteTime() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DeviceInterfaceUpsertOne) ClearDeleteTime() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearDeleteTime()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DeviceInterfaceUpsertOne) SetDeviceID(v string) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateDeviceID() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateDeviceID()
	})
}

// SetName sets the "name" field.
func (u *DeviceInterfaceUpsertOne) SetName(v string) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateName() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateName()
	})
}

// SetMACAddress sets the "mac_address" field.
func (u *DeviceInterfaceUpsertOne) SetMACAddress(v string) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetMACAddress(v)
	})
}

// UpdateMACAddress sets the "mac_address" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateMACAddress() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateMACAddress()
	})
}

// ClearMACAddress clears the value of the "mac_address" field.
func (u *DeviceInterfaceUpsertOne) ClearMACAddress() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearMACAddress()
	})
}

// SetInterfaceType sets the "interface_type" field.
func (u *DeviceInterfaceUpsertOne) SetInterfaceType(v string) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetInterfaceType(v)
	})
}

// UpdateInterfaceType sets the "interface_type" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateInterfaceType() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateInterfaceType()
	})
}

// ClearInterfaceType clears the value of the "interface_type" field.
func (u *DeviceInterfaceUpsertOne) ClearInterfaceType() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearInterfaceType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DeviceInterfaceUpsertOne) SetEnabled(v bool) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateEnabled() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateEnabled()
	})
}

// SetSpeedMbps sets the "speed_mbps" field.
func (u *DeviceInterfaceUpsertOne) SetSpeedMbps(v int32) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetSpeedMbps(v)
	})
}

// AddSpeedMbps adds v to the "speed_mbps" field.
func (u *DeviceInterfaceUpsertOne) AddSpeedMbps(v int32) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.AddSpeedMbps(v)
	})
}

// UpdateSpeedMbps sets the "speed_mbps" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateSpeedMbps() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateSpeedMbps()
	})
}

// ClearSpeedMbps clears the value of the "speed_mbps" field.
func (u *DeviceInterfaceUpsertOne) ClearSpeedMbps() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearSpeedMbps()
	})
}

// SetDescription sets the "description" field.
func (u *DeviceInterfaceUpsertOne) SetDescription(v string) *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertOne) UpdateDescription() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *DeviceInterfaceUpsertOne) ClearDescription() *DeviceInterfaceUpsertOne {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *DeviceInterfaceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceInterfaceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceInterfaceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceInterfaceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeviceInterfaceUpsertOne.ID is not supported by MySQL driver. Use DeviceInterfaceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceInterfaceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceInterfaceCreateBulk is the builder for creating many DeviceInterface entities in bulk.
type DeviceInterfaceCreateBulk struct {
	config
	err      error
	builders []*DeviceInterfaceCreate
	conflict []sql.ConflictOption
}

// Save creates the DeviceInterface entities in the database.
func (_c *DeviceInterfaceCreateBulk) Save(ctx context.Context) ([]*DeviceInterface, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceInterface, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceInterfaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceInterfaceCreateBulk) SaveX(ctx context.Context) []*DeviceInterface {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceInterfaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceInterfaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceInterface.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceInterfaceUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceInterfaceCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceInterfaceUpsertBulk {
	_c.conflict = opts
	return &DeviceInterfaceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceInterface.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceInterfaceCreateBulk) OnConflictColumns(columns ...string) *DeviceInterfaceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceInterfaceUpsertBulk{
		create: _c,
	}
}

// DeviceInterfaceUpsertBulk is the builder for "upsert"-ing
// a bulk of DeviceInterface nodes.
type DeviceInterfaceUpsertBulk struct {
	create *DeviceInterfaceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeviceInterface.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deviceinterface.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceInterfaceUpsertBulk) UpdateNewValues() *DeviceInterfaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(deviceinterface.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(deviceinterface.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceInterface.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceInterfaceUpsertBulk) Ignore() *DeviceInterfaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceInterfaceUpsertBulk) DoNothing() *DeviceInterfaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceInterfaceCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceInterfaceUpsertBulk) Update(set func(*DeviceInterfaceUpsert)) *DeviceInterfaceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceInterfaceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DeviceInterfaceUpsertBulk) SetUpdateTime(v time.Time) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateUpdateTime() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DeviceInterfaceUpsertBulk) ClearUpdateTime() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *DeviceInterfaceUpsertBulk) SetDeleteTime(v time.Time) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateDeleteTime() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DeviceInterfaceUpsertBulk) ClearDeleteTime() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearDeleteTime()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DeviceInterfaceUpsertBulk) SetDeviceID(v string) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateDeviceID() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateDeviceID()
	})
}

// SetName sets the "name" field.
func (u *DeviceInterfaceUpsertBulk) SetName(v string) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateName() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateName()
	})
}

// SetMACAddress sets the "mac_address" field.
func (u *DeviceInterfaceUpsertBulk) SetMACAddress(v string) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetMACAddress(v)
	})
}

// UpdateMACAddress sets the "mac_address" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateMACAddress() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateMACAddress()
	})
}

// ClearMACAddress clears the value of the "mac_address" field.
func (u *DeviceInterfaceUpsertBulk) ClearMACAddress() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearMACAddress()
	})
}

// SetInterfaceType sets the "interface_type" field.
func (u *DeviceInterfaceUpsertBulk) SetInterfaceType(v string) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetInterfaceType(v)
	})
}

// UpdateInterfaceType sets the "interface_type" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateInterfaceType() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateInterfaceType()
	})
}

// ClearInterfaceType clears the value of the "interface_type" field.
func (u *DeviceInterfaceUpsertBulk) ClearInterfaceType() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearInterfaceType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DeviceInterfaceUpsertBulk) SetEnabled(v bool) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateEnabled() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateEnabled()
	})
}

// SetSpeedMbps sets the "speed_mbps" field.
func (u *DeviceInterfaceUpsertBulk) SetSpeedMbps(v int32) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetSpeedMbps(v)
	})
}

// AddSpeedMbps adds v to the "speed_mbps" field.
func (u *DeviceInterfaceUpsertBulk) AddSpeedMbps(v int32) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.AddSpeedMbps(v)
	})
}

// UpdateSpeedMbps sets the "speed_mbps" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateSpeedMbps() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateSpeedMbps()
	})
}

// ClearSpeedMbps clears the value of the "speed_mbps" field.
func (u *DeviceInterfaceUpsertBulk) ClearSpeedMbps() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearSpeedMbps()
	})
}

// SetDescription sets the "description" field.
func (u *DeviceInterfaceUpsertBulk) SetDescription(v string) *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DeviceInterfaceUpsertBulk) UpdateDescription() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *DeviceInterfaceUpsertBulk) ClearDescription() *DeviceInterfaceUpsertBulk {
	return u.Update(func(s *DeviceInterfaceUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *DeviceInterfaceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeviceInterfaceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceInterfaceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceInterfaceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
