// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/dnsconfig"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// DnsConfigUpdate is the builder for updating DnsConfig entities.
type DnsConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *DnsConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DnsConfigUpdate builder.
func (_u *DnsConfigUpdate) Where(ps ...predicate.DnsConfig) *DnsConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *DnsConfigUpdate) SetCreateBy(v uint32) *DnsConfigUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableCreateBy(v *uint32) *DnsConfigUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *DnsConfigUpdate) AddCreateBy(v int32) *DnsConfigUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *DnsConfigUpdate) ClearCreateBy() *DnsConfigUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *DnsConfigUpdate) SetUpdateBy(v uint32) *DnsConfigUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableUpdateBy(v *uint32) *DnsConfigUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *DnsConfigUpdate) AddUpdateBy(v int32) *DnsConfigUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *DnsConfigUpdate) ClearUpdateBy() *DnsConfigUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DnsConfigUpdate) SetUpdateTime(v time.Time) *DnsConfigUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableUpdateTime(v *time.Time) *DnsConfigUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DnsConfigUpdate) ClearUpdateTime() *DnsConfigUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DnsConfigUpdate) SetDeleteTime(v time.Time) *DnsConfigUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableDeleteTime(v *time.Time) *DnsConfigUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DnsConfigUpdate) ClearDeleteTime() *DnsConfigUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDNSServers sets the "dns_servers" field.
func (_u *DnsConfigUpdate) SetDNSServers(v []string) *DnsConfigUpdate {
	_u.mutation.SetDNSServers(v)
	return _u
}

// AppendDNSServers appends value to the "dns_servers" field.
func (_u *DnsConfigUpdate) AppendDNSServers(v []string) *DnsConfigUpdate {
	_u.mutation.AppendDNSServers(v)
	return _u
}

// ClearDNSServers clears the value of the "dns_servers" field.
func (_u *DnsConfigUpdate) ClearDNSServers() *DnsConfigUpdate {
	_u.mutation.ClearDNSServers()
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *DnsConfigUpdate) SetTimeoutMs(v int32) *DnsConfigUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableTimeoutMs(v *int32) *DnsConfigUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *DnsConfigUpdate) AddTimeoutMs(v int32) *DnsConfigUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetUseSystemDNSFallback sets the "use_system_dns_fallback" field.
func (_u *DnsConfigUpdate) SetUseSystemDNSFallback(v bool) *DnsConfigUpdate {
	_u.mutation.SetUseSystemDNSFallback(v)
	return _u
}

// SetNillableUseSystemDNSFallback sets the "use_system_dns_fallback" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableUseSystemDNSFallback(v *bool) *DnsConfigUpdate {
	if v != nil {
		_u.SetUseSystemDNSFallback(*v)
	}
	return _u
}

// SetReverseDNSEnabled sets the "reverse_dns_enabled" field.
func (_u *DnsConfigUpdate) SetReverseDNSEnabled(v bool) *DnsConfigUpdate {
	_u.mutation.SetReverseDNSEnabled(v)
	return _u
}

// SetNillableReverseDNSEnabled sets the "reverse_dns_enabled" field if the given value is not nil.
func (_u *DnsConfigUpdate) SetNillableReverseDNSEnabled(v *bool) *DnsConfigUpdate {
	if v != nil {
		_u.SetReverseDNSEnabled(*v)
	}
	return _u
}

// Mutation returns the DnsConfigMutation object of the builder.
func (_u *DnsConfigUpdate) Mutation() *DnsConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DnsConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DnsConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DnsConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DnsConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DnsConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DnsConfigUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DnsConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dnsconfig.Table, dnsconfig.Columns, sqlgraph.NewFieldSpec(dnsconfig.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(dnsconfig.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(dnsconfig.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(dnsconfig.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(dnsconfig.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(dnsconfig.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(dnsconfig.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(dnsconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(dnsconfig.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(dnsconfig.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dnsconfig.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DNSServers(); ok {
		_spec.SetField(dnsconfig.FieldDNSServers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDNSServers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dnsconfig.FieldDNSServers, value)
		})
	}
	if _u.mutation.DNSServersCleared() {
		_spec.ClearField(dnsconfig.FieldDNSServers, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(dnsconfig.FieldTimeoutMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(dnsconfig.FieldTimeoutMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UseSystemDNSFallback(); ok {
		_spec.SetField(dnsconfig.FieldUseSystemDNSFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReverseDNSEnabled(); ok {
		_spec.SetField(dnsconfig.FieldReverseDNSEnabled, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DnsConfigUpdateOne is the builder for updating a single DnsConfig entity.
type DnsConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DnsConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *DnsConfigUpdateOne) SetCreateBy(v uint32) *DnsConfigUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableCreateBy(v *uint32) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *DnsConfigUpdateOne) AddCreateBy(v int32) *DnsConfigUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *DnsConfigUpdateOne) ClearCreateBy() *DnsConfigUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *DnsConfigUpdateOne) SetUpdateBy(v uint32) *DnsConfigUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableUpdateBy(v *uint32) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *DnsConfigUpdateOne) AddUpdateBy(v int32) *DnsConfigUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *DnsConfigUpdateOne) ClearUpdateBy() *DnsConfigUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DnsConfigUpdateOne) SetUpdateTime(v time.Time) *DnsConfigUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableUpdateTime(v *time.Time) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DnsConfigUpdateOne) ClearUpdateTime() *DnsConfigUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DnsConfigUpdateOne) SetDeleteTime(v time.Time) *DnsConfigUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableDeleteTime(v *time.Time) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DnsConfigUpdateOne) ClearDeleteTime() *DnsConfigUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDNSServers sets the "dns_servers" field.
func (_u *DnsConfigUpdateOne) SetDNSServers(v []string) *DnsConfigUpdateOne {
	_u.mutation.SetDNSServers(v)
	return _u
}

// AppendDNSServers appends value to the "dns_servers" field.
func (_u *DnsConfigUpdateOne) AppendDNSServers(v []string) *DnsConfigUpdateOne {
	_u.mutation.AppendDNSServers(v)
	return _u
}

// ClearDNSServers clears the value of the "dns_servers" field.
func (_u *DnsConfigUpdateOne) ClearDNSServers() *DnsConfigUpdateOne {
	_u.mutation.ClearDNSServers()
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *DnsConfigUpdateOne) SetTimeoutMs(v int32) *DnsConfigUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableTimeoutMs(v *int32) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *DnsConfigUpdateOne) AddTimeoutMs(v int32) *DnsConfigUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetUseSystemDNSFallback sets the "use_system_dns_fallback" field.
func (_u *DnsConfigUpdateOne) SetUseSystemDNSFallback(v bool) *DnsConfigUpdateOne {
	_u.mutation.SetUseSystemDNSFallback(v)
	return _u
}

// SetNillableUseSystemDNSFallback sets the "use_system_dns_fallback" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableUseSystemDNSFallback(v *bool) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetUseSystemDNSFallback(*v)
	}
	return _u
}

// SetReverseDNSEnabled sets the "reverse_dns_enabled" field.
func (_u *DnsConfigUpdateOne) SetReverseDNSEnabled(v bool) *DnsConfigUpdateOne {
	_u.mutation.SetReverseDNSEnabled(v)
	return _u
}

// SetNillableReverseDNSEnabled sets the "reverse_dns_enabled" field if the given value is not nil.
func (_u *DnsConfigUpdateOne) SetNillableReverseDNSEnabled(v *bool) *DnsConfigUpdateOne {
	if v != nil {
		_u.SetReverseDNSEnabled(*v)
	}
	return _u
}

// Mutation returns the DnsConfigMutation object of the builder.
func (_u *DnsConfigUpdateOne) Mutation() *DnsConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the DnsConfigUpdate builder.
func (_u *DnsConfigUpdateOne) Where(ps ...predicate.DnsConfig) *DnsConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DnsConfigUpdateOne) Select(field string, fields ...string) *DnsConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DnsConfig entity.
func (_u *DnsConfigUpdateOne) Save(ctx context.Context) (*DnsConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DnsConfigUpdateOne) SaveX(ctx context.Context) *DnsConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DnsConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DnsConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DnsConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DnsConfigUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DnsConfigUpdateOne) sqlSave(ctx context.Context) (_node *DnsConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(dnsconfig.Table, dnsconfig.Columns, sqlgraph.NewFieldSpec(dnsconfig.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DnsConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnsconfig.FieldID)
		for _, f := range fields {
			if !dnsconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dnsconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(dnsconfig.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(dnsconfig.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(dnsconfig.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(dnsconfig.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(dnsconfig.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(dnsconfig.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(dnsconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(dnsconfig.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(dnsconfig.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(dnsconfig.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(dnsconfig.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DNSServers(); ok {
		_spec.SetField(dnsconfig.FieldDNSServers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDNSServers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dnsconfig.FieldDNSServers, value)
		})
	}
	if _u.mutation.DNSServersCleared() {
		_spec.ClearField(dnsconfig.FieldDNSServers, field.TypeJSON)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(dnsconfig.FieldTimeoutMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(dnsconfig.FieldTimeoutMs, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UseSystemDNSFallback(); ok {
		_spec.SetField(dnsconfig.FieldUseSystemDNSFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReverseDNSEnabled(); ok {
		_spec.SetField(dnsconfig.FieldReverseDNSEnabled, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DnsConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
