// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/device"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/hostgroup"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/hostgroupmember"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// HostGroupMember is the model entity for the HostGroupMember schema.
type HostGroupMember struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// Host Group ID
	HostGroupID string `json:"host_group_id,omitempty"`
	// Device ID
	DeviceID string `json:"device_id,omitempty"`
	// Order/sequence in the group
	Sequence int32 `json:"sequence,omitempty"`
	// Creation timestamp
	CreateTime *time.Time `json:"create_time,omitempty"`
	// Last update timestamp
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HostGroupMemberQuery when eager-loading is set.
	Edges        HostGroupMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HostGroupMemberEdges holds the relations/edges for other nodes in the graph.
type HostGroupMemberEdges struct {
	// Group holds the value of the group edge.
	Group *HostGroup `json:"group,omitempty"`
	// Device holds the value of the device edge.
	Device *Device `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HostGroupMemberEdges) GroupOrErr() (*HostGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: hostgroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HostGroupMemberEdges) DeviceOrErr() (*Device, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: device.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HostGroupMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hostgroupmember.FieldSequence:
			values[i] = new(sql.NullInt64)
		case hostgroupmember.FieldID, hostgroupmember.FieldHostGroupID, hostgroupmember.FieldDeviceID:
			values[i] = new(sql.NullString)
		case hostgroupmember.FieldCreateTime, hostgroupmember.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HostGroupMember fields.
func (_m *HostGroupMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hostgroupmember.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case hostgroupmember.FieldHostGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host_group_id", values[i])
			} else if value.Valid {
				_m.HostGroupID = value.String
			}
		case hostgroupmember.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case hostgroupmember.FieldSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence", values[i])
			} else if value.Valid {
				_m.Sequence = int32(value.Int64)
			}
		case hostgroupmember.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case hostgroupmember.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HostGroupMember.
// This includes values selected through modifiers, order, etc.
func (_m *HostGroupMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the HostGroupMember entity.
func (_m *HostGroupMember) QueryGroup() *HostGroupQuery {
	return NewHostGroupMemberClient(_m.config).QueryGroup(_m)
}

// QueryDevice queries the "device" edge of the HostGroupMember entity.
func (_m *HostGroupMember) QueryDevice() *DeviceQuery {
	return NewHostGroupMemberClient(_m.config).QueryDevice(_m)
}

// Update returns a builder for updating this HostGroupMember.
// Note that you need to call HostGroupMember.Unwrap() before calling this method if this HostGroupMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HostGroupMember) Update() *HostGroupMemberUpdateOne {
	return NewHostGroupMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HostGroupMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HostGroupMember) Unwrap() *HostGroupMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HostGroupMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HostGroupMember) String() string {
	var builder strings.Builder
	builder.WriteString("HostGroupMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("host_group_id=")
	builder.WriteString(_m.HostGroupID)
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sequence))
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// HostGroupMembers is a parsable slice of HostGroupMember.
type HostGroupMembers []*HostGroupMember
