// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/ipgroup"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/ipgroupmember"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IpGroupMemberUpdate is the builder for updating IpGroupMember entities.
type IpGroupMemberUpdate struct {
	config
	hooks     []Hook
	mutation  *IpGroupMemberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the IpGroupMemberUpdate builder.
func (_u *IpGroupMemberUpdate) Where(ps ...predicate.IpGroupMember) *IpGroupMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIPGroupID sets the "ip_group_id" field.
func (_u *IpGroupMemberUpdate) SetIPGroupID(v string) *IpGroupMemberUpdate {
	_u.mutation.SetIPGroupID(v)
	return _u
}

// SetNillableIPGroupID sets the "ip_group_id" field if the given value is not nil.
func (_u *IpGroupMemberUpdate) SetNillableIPGroupID(v *string) *IpGroupMemberUpdate {
	if v != nil {
		_u.SetIPGroupID(*v)
	}
	return _u
}

// SetMemberType sets the "member_type" field.
func (_u *IpGroupMemberUpdate) SetMemberType(v int32) *IpGroupMemberUpdate {
	_u.mutation.ResetMemberType()
	_u.mutation.SetMemberType(v)
	return _u
}

// SetNillableMemberType sets the "member_type" field if the given value is not nil.
func (_u *IpGroupMemberUpdate) SetNillableMemberType(v *int32) *IpGroupMemberUpdate {
	if v != nil {
		_u.SetMemberType(*v)
	}
	return _u
}

// AddMemberType adds value to the "member_type" field.
func (_u *IpGroupMemberUpdate) AddMemberType(v int32) *IpGroupMemberUpdate {
	_u.mutation.AddMemberType(v)
	return _u
}

// SetValue sets the "value" field.
func (_u *IpGroupMemberUpdate) SetValue(v string) *IpGroupMemberUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *IpGroupMemberUpdate) SetNillableValue(v *string) *IpGroupMemberUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *IpGroupMemberUpdate) SetDescription(v string) *IpGroupMemberUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *IpGroupMemberUpdate) SetNillableDescription(v *string) *IpGroupMemberUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *IpGroupMemberUpdate) ClearDescription() *IpGroupMemberUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *IpGroupMemberUpdate) SetSequence(v int32) *IpGroupMemberUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *IpGroupMemberUpdate) SetNillableSequence(v *int32) *IpGroupMemberUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *IpGroupMemberUpdate) AddSequence(v int32) *IpGroupMemberUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *IpGroupMemberUpdate) SetCreateTime(v time.Time) *IpGroupMemberUpdate {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *IpGroupMemberUpdate) SetNillableCreateTime(v *time.Time) *IpGroupMemberUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// ClearCreateTime clears the value of the "create_time" field.
func (_u *IpGroupMemberUpdate) ClearCreateTime() *IpGroupMemberUpdate {
	_u.mutation.ClearCreateTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *IpGroupMemberUpdate) SetUpdateTime(v time.Time) *IpGroupMemberUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *IpGroupMemberUpdate) SetNillableUpdateTime(v *time.Time) *IpGroupMemberUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *IpGroupMemberUpdate) ClearUpdateTime() *IpGroupMemberUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetGroupID sets the "group" edge to the IpGroup entity by ID.
func (_u *IpGroupMemberUpdate) SetGroupID(id string) *IpGroupMemberUpdate {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the IpGroup entity.
func (_u *IpGroupMemberUpdate) SetGroup(v *IpGroup) *IpGroupMemberUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the IpGroupMemberMutation object of the builder.
func (_u *IpGroupMemberUpdate) Mutation() *IpGroupMemberMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the IpGroup entity.
func (_u *IpGroupMemberUpdate) ClearGroup() *IpGroupMemberUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IpGroupMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IpGroupMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IpGroupMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IpGroupMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IpGroupMemberUpdate) check() error {
	if v, ok := _u.mutation.IPGroupID(); ok {
		if err := ipgroupmember.IPGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "ip_group_id", err: fmt.Errorf(`ent: validator failed for field "IpGroupMember.ip_group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := ipgroupmember.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "IpGroupMember.value": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IpGroupMember.group"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *IpGroupMemberUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IpGroupMemberUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *IpGroupMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ipgroupmember.Table, ipgroupmember.Columns, sqlgraph.NewFieldSpec(ipgroupmember.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MemberType(); ok {
		_spec.SetField(ipgroupmember.FieldMemberType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMemberType(); ok {
		_spec.AddField(ipgroupmember.FieldMemberType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(ipgroupmember.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ipgroupmember.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ipgroupmember.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(ipgroupmember.FieldSequence, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(ipgroupmember.FieldSequence, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(ipgroupmember.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(ipgroupmember.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ipgroupmember.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(ipgroupmember.FieldUpdateTime, field.TypeTime)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ipgroupmember.GroupTable,
			Columns: []string{ipgroupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipgroup.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ipgroupmember.GroupTable,
			Columns: []string{ipgroupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipgroup.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipgroupmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IpGroupMemberUpdateOne is the builder for updating a single IpGroupMember entity.
type IpGroupMemberUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *IpGroupMemberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetIPGroupID sets the "ip_group_id" field.
func (_u *IpGroupMemberUpdateOne) SetIPGroupID(v string) *IpGroupMemberUpdateOne {
	_u.mutation.SetIPGroupID(v)
	return _u
}

// SetNillableIPGroupID sets the "ip_group_id" field if the given value is not nil.
func (_u *IpGroupMemberUpdateOne) SetNillableIPGroupID(v *string) *IpGroupMemberUpdateOne {
	if v != nil {
		_u.SetIPGroupID(*v)
	}
	return _u
}

// SetMemberType sets the "member_type" field.
func (_u *IpGroupMemberUpdateOne) SetMemberType(v int32) *IpGroupMemberUpdateOne {
	_u.mutation.ResetMemberType()
	_u.mutation.SetMemberType(v)
	return _u
}

// SetNillableMemberType sets the "member_type" field if the given value is not nil.
func (_u *IpGroupMemberUpdateOne) SetNillableMemberType(v *int32) *IpGroupMemberUpdateOne {
	if v != nil {
		_u.SetMemberType(*v)
	}
	return _u
}

// AddMemberType adds value to the "member_type" field.
func (_u *IpGroupMemberUpdateOne) AddMemberType(v int32) *IpGroupMemberUpdateOne {
	_u.mutation.AddMemberType(v)
	return _u
}

// SetValue sets the "value" field.
func (_u *IpGroupMemberUpdateOne) SetValue(v string) *IpGroupMemberUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *IpGroupMemberUpdateOne) SetNillableValue(v *string) *IpGroupMemberUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *IpGroupMemberUpdateOne) SetDescription(v string) *IpGroupMemberUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *IpGroupMemberUpdateOne) SetNillableDescription(v *string) *IpGroupMemberUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *IpGroupMemberUpdateOne) ClearDescription() *IpGroupMemberUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *IpGroupMemberUpdateOne) SetSequence(v int32) *IpGroupMemberUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *IpGroupMemberUpdateOne) SetNillableSequence(v *int32) *IpGroupMemberUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *IpGroupMemberUpdateOne) AddSequence(v int32) *IpGroupMemberUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *IpGroupMemberUpdateOne) SetCreateTime(v time.Time) *IpGroupMemberUpdateOne {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *IpGroupMemberUpdateOne) SetNillableCreateTime(v *time.Time) *IpGroupMemberUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// ClearCreateTime clears the value of the "create_time" field.
func (_u *IpGroupMemberUpdateOne) ClearCreateTime() *IpGroupMemberUpdateOne {
	_u.mutation.ClearCreateTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *IpGroupMemberUpdateOne) SetUpdateTime(v time.Time) *IpGroupMemberUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *IpGroupMemberUpdateOne) SetNillableUpdateTime(v *time.Time) *IpGroupMemberUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *IpGroupMemberUpdateOne) ClearUpdateTime() *IpGroupMemberUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetGroupID sets the "group" edge to the IpGroup entity by ID.
func (_u *IpGroupMemberUpdateOne) SetGroupID(id string) *IpGroupMemberUpdateOne {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the IpGroup entity.
func (_u *IpGroupMemberUpdateOne) SetGroup(v *IpGroup) *IpGroupMemberUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the IpGroupMemberMutation object of the builder.
func (_u *IpGroupMemberUpdateOne) Mutation() *IpGroupMemberMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the IpGroup entity.
func (_u *IpGroupMemberUpdateOne) ClearGroup() *IpGroupMemberUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the IpGroupMemberUpdate builder.
func (_u *IpGroupMemberUpdateOne) Where(ps ...predicate.IpGroupMember) *IpGroupMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IpGroupMemberUpdateOne) Select(field string, fields ...string) *IpGroupMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IpGroupMember entity.
func (_u *IpGroupMemberUpdateOne) Save(ctx context.Context) (*IpGroupMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IpGroupMemberUpdateOne) SaveX(ctx context.Context) *IpGroupMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IpGroupMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IpGroupMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IpGroupMemberUpdateOne) check() error {
	if v, ok := _u.mutation.IPGroupID(); ok {
		if err := ipgroupmember.IPGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "ip_group_id", err: fmt.Errorf(`ent: validator failed for field "IpGroupMember.ip_group_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := ipgroupmember.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "IpGroupMember.value": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IpGroupMember.group"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *IpGroupMemberUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IpGroupMemberUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *IpGroupMemberUpdateOne) sqlSave(ctx context.Context) (_node *IpGroupMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ipgroupmember.Table, ipgroupmember.Columns, sqlgraph.NewFieldSpec(ipgroupmember.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IpGroupMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ipgroupmember.FieldID)
		for _, f := range fields {
			if !ipgroupmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ipgroupmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MemberType(); ok {
		_spec.SetField(ipgroupmember.FieldMemberType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMemberType(); ok {
		_spec.AddField(ipgroupmember.FieldMemberType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(ipgroupmember.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ipgroupmember.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ipgroupmember.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(ipgroupmember.FieldSequence, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(ipgroupmember.FieldSequence, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(ipgroupmember.FieldCreateTime, field.TypeTime, value)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(ipgroupmember.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ipgroupmember.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(ipgroupmember.FieldUpdateTime, field.TypeTime)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ipgroupmember.GroupTable,
			Columns: []string{ipgroupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipgroup.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ipgroupmember.GroupTable,
			Columns: []string{ipgroupmember.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ipgroup.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &IpGroupMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipgroupmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
