// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/ipscanjob"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/subnet"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IpScanJobCreate is the builder for creating a IpScanJob entity.
type IpScanJobCreate struct {
	config
	mutation *IpScanJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *IpScanJobCreate) SetCreateBy(v uint32) *IpScanJobCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableCreateBy(v *uint32) *IpScanJobCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *IpScanJobCreate) SetUpdateBy(v uint32) *IpScanJobCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableUpdateBy(v *uint32) *IpScanJobCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *IpScanJobCreate) SetCreateTime(v time.Time) *IpScanJobCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableCreateTime(v *time.Time) *IpScanJobCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *IpScanJobCreate) SetUpdateTime(v time.Time) *IpScanJobCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableUpdateTime(v *time.Time) *IpScanJobCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *IpScanJobCreate) SetDeleteTime(v time.Time) *IpScanJobCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableDeleteTime(v *time.Time) *IpScanJobCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *IpScanJobCreate) SetTenantID(v uint32) *IpScanJobCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableTenantID(v *uint32) *IpScanJobCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetSubnetID sets the "subnet_id" field.
func (_c *IpScanJobCreate) SetSubnetID(v string) *IpScanJobCreate {
	_c.mutation.SetSubnetID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *IpScanJobCreate) SetStatus(v ipscanjob.Status) *IpScanJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableStatus(v *ipscanjob.Status) *IpScanJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *IpScanJobCreate) SetProgress(v int32) *IpScanJobCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableProgress(v *int32) *IpScanJobCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetStatusMessage sets the "status_message" field.
func (_c *IpScanJobCreate) SetStatusMessage(v string) *IpScanJobCreate {
	_c.mutation.SetStatusMessage(v)
	return _c
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableStatusMessage(v *string) *IpScanJobCreate {
	if v != nil {
		_c.SetStatusMessage(*v)
	}
	return _c
}

// SetTotalAddresses sets the "total_addresses" field.
func (_c *IpScanJobCreate) SetTotalAddresses(v int64) *IpScanJobCreate {
	_c.mutation.SetTotalAddresses(v)
	return _c
}

// SetNillableTotalAddresses sets the "total_addresses" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableTotalAddresses(v *int64) *IpScanJobCreate {
	if v != nil {
		_c.SetTotalAddresses(*v)
	}
	return _c
}

// SetScannedCount sets the "scanned_count" field.
func (_c *IpScanJobCreate) SetScannedCount(v int64) *IpScanJobCreate {
	_c.mutation.SetScannedCount(v)
	return _c
}

// SetNillableScannedCount sets the "scanned_count" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableScannedCount(v *int64) *IpScanJobCreate {
	if v != nil {
		_c.SetScannedCount(*v)
	}
	return _c
}

// SetAliveCount sets the "alive_count" field.
func (_c *IpScanJobCreate) SetAliveCount(v int64) *IpScanJobCreate {
	_c.mutation.SetAliveCount(v)
	return _c
}

// SetNillableAliveCount sets the "alive_count" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableAliveCount(v *int64) *IpScanJobCreate {
	if v != nil {
		_c.SetAliveCount(*v)
	}
	return _c
}

// SetNewCount sets the "new_count" field.
func (_c *IpScanJobCreate) SetNewCount(v int64) *IpScanJobCreate {
	_c.mutation.SetNewCount(v)
	return _c
}

// SetNillableNewCount sets the "new_count" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableNewCount(v *int64) *IpScanJobCreate {
	if v != nil {
		_c.SetNewCount(*v)
	}
	return _c
}

// SetUpdatedCount sets the "updated_count" field.
func (_c *IpScanJobCreate) SetUpdatedCount(v int64) *IpScanJobCreate {
	_c.mutation.SetUpdatedCount(v)
	return _c
}

// SetNillableUpdatedCount sets the "updated_count" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableUpdatedCount(v *int64) *IpScanJobCreate {
	if v != nil {
		_c.SetUpdatedCount(*v)
	}
	return _c
}

// SetTriggeredBy sets the "triggered_by" field.
func (_c *IpScanJobCreate) SetTriggeredBy(v ipscanjob.TriggeredBy) *IpScanJobCreate {
	_c.mutation.SetTriggeredBy(v)
	return _c
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableTriggeredBy(v *ipscanjob.TriggeredBy) *IpScanJobCreate {
	if v != nil {
		_c.SetTriggeredBy(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *IpScanJobCreate) SetRetryCount(v int32) *IpScanJobCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableRetryCount(v *int32) *IpScanJobCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetMaxRetries sets the "max_retries" field.
func (_c *IpScanJobCreate) SetMaxRetries(v int32) *IpScanJobCreate {
	_c.mutation.SetMaxRetries(v)
	return _c
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableMaxRetries(v *int32) *IpScanJobCreate {
	if v != nil {
		_c.SetMaxRetries(*v)
	}
	return _c
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_c *IpScanJobCreate) SetNextRetryAt(v time.Time) *IpScanJobCreate {
	_c.mutation.SetNextRetryAt(v)
	return _c
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableNextRetryAt(v *time.Time) *IpScanJobCreate {
	if v != nil {
		_c.SetNextRetryAt(*v)
	}
	return _c
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_c *IpScanJobCreate) SetTimeoutMs(v int32) *IpScanJobCreate {
	_c.mutation.SetTimeoutMs(v)
	return _c
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableTimeoutMs(v *int32) *IpScanJobCreate {
	if v != nil {
		_c.SetTimeoutMs(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *IpScanJobCreate) SetConcurrency(v int32) *IpScanJobCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableConcurrency(v *int32) *IpScanJobCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetSkipReverseDNS sets the "skip_reverse_dns" field.
func (_c *IpScanJobCreate) SetSkipReverseDNS(v bool) *IpScanJobCreate {
	_c.mutation.SetSkipReverseDNS(v)
	return _c
}

// SetNillableSkipReverseDNS sets the "skip_reverse_dns" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableSkipReverseDNS(v *bool) *IpScanJobCreate {
	if v != nil {
		_c.SetSkipReverseDNS(*v)
	}
	return _c
}

// SetTCPProbePorts sets the "tcp_probe_ports" field.
func (_c *IpScanJobCreate) SetTCPProbePorts(v string) *IpScanJobCreate {
	_c.mutation.SetTCPProbePorts(v)
	return _c
}

// SetNillableTCPProbePorts sets the "tcp_probe_ports" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableTCPProbePorts(v *string) *IpScanJobCreate {
	if v != nil {
		_c.SetTCPProbePorts(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *IpScanJobCreate) SetStartedAt(v time.Time) *IpScanJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableStartedAt(v *time.Time) *IpScanJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *IpScanJobCreate) SetCompletedAt(v time.Time) *IpScanJobCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *IpScanJobCreate) SetNillableCompletedAt(v *time.Time) *IpScanJobCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IpScanJobCreate) SetID(v string) *IpScanJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSubnet sets the "subnet" edge to the Subnet entity.
func (_c *IpScanJobCreate) SetSubnet(v *Subnet) *IpScanJobCreate {
	return _c.SetSubnetID(v.ID)
}

// Mutation returns the IpScanJobMutation object of the builder.
func (_c *IpScanJobCreate) Mutation() *IpScanJobMutation {
	return _c.mutation
}

// Save creates the IpScanJob in the database.
func (_c *IpScanJobCreate) Save(ctx context.Context) (*IpScanJob, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IpScanJobCreate) SaveX(ctx context.Context) *IpScanJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IpScanJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IpScanJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IpScanJobCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := ipscanjob.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ipscanjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := ipscanjob.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.TotalAddresses(); !ok {
		v := ipscanjob.DefaultTotalAddresses
		_c.mutation.SetTotalAddresses(v)
	}
	if _, ok := _c.mutation.ScannedCount(); !ok {
		v := ipscanjob.DefaultScannedCount
		_c.mutation.SetScannedCount(v)
	}
	if _, ok := _c.mutation.AliveCount(); !ok {
		v := ipscanjob.DefaultAliveCount
		_c.mutation.SetAliveCount(v)
	}
	if _, ok := _c.mutation.NewCount(); !ok {
		v := ipscanjob.DefaultNewCount
		_c.mutation.SetNewCount(v)
	}
	if _, ok := _c.mutation.UpdatedCount(); !ok {
		v := ipscanjob.DefaultUpdatedCount
		_c.mutation.SetUpdatedCount(v)
	}
	if _, ok := _c.mutation.TriggeredBy(); !ok {
		v := ipscanjob.DefaultTriggeredBy
		_c.mutation.SetTriggeredBy(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := ipscanjob.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.MaxRetries(); !ok {
		v := ipscanjob.DefaultMaxRetries
		_c.mutation.SetMaxRetries(v)
	}
	if _, ok := _c.mutation.TimeoutMs(); !ok {
		v := ipscanjob.DefaultTimeoutMs
		_c.mutation.SetTimeoutMs(v)
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := ipscanjob.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	if _, ok := _c.mutation.SkipReverseDNS(); !ok {
		v := ipscanjob.DefaultSkipReverseDNS
		_c.mutation.SetSkipReverseDNS(v)
	}
	if _, ok := _c.mutation.TCPProbePorts(); !ok {
		v := ipscanjob.DefaultTCPProbePorts
		_c.mutation.SetTCPProbePorts(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *IpScanJobCreate) check() error {
	if _, ok := _c.mutation.SubnetID(); !ok {
		return &ValidationError{Name: "subnet_id", err: errors.New(`ent: missing required field "IpScanJob.subnet_id"`)}
	}
	if v, ok := _c.mutation.SubnetID(); ok {
		if err := ipscanjob.SubnetIDValidator(v); err != nil {
			return &ValidationError{Name: "subnet_id", err: fmt.Errorf(`ent: validator failed for field "IpScanJob.subnet_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IpScanJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ipscanjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IpScanJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "IpScanJob.progress"`)}
	}
	if _, ok := _c.mutation.TotalAddresses(); !ok {
		return &ValidationError{Name: "total_addresses", err: errors.New(`ent: missing required field "IpScanJob.total_addresses"`)}
	}
	if _, ok := _c.mutation.ScannedCount(); !ok {
		return &ValidationError{Name: "scanned_count", err: errors.New(`ent: missing required field "IpScanJob.scanned_count"`)}
	}
	if _, ok := _c.mutation.AliveCount(); !ok {
		return &ValidationError{Name: "alive_count", err: errors.New(`ent: missing required field "IpScanJob.alive_count"`)}
	}
	if _, ok := _c.mutation.NewCount(); !ok {
		return &ValidationError{Name: "new_count", err: errors.New(`ent: missing required field "IpScanJob.new_count"`)}
	}
	if _, ok := _c.mutation.UpdatedCount(); !ok {
		return &ValidationError{Name: "updated_count", err: errors.New(`ent: missing required field "IpScanJob.updated_count"`)}
	}
	if _, ok := _c.mutation.TriggeredBy(); !ok {
		return &ValidationError{Name: "triggered_by", err: errors.New(`ent: missing required field "IpScanJob.triggered_by"`)}
	}
	if v, ok := _c.mutation.TriggeredBy(); ok {
		if err := ipscanjob.TriggeredByValidator(v); err != nil {
			return &ValidationError{Name: "triggered_by", err: fmt.Errorf(`ent: validator failed for field "IpScanJob.triggered_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "IpScanJob.retry_count"`)}
	}
	if _, ok := _c.mutation.MaxRetries(); !ok {
		return &ValidationError{Name: "max_retries", err: errors.New(`ent: missing required field "IpScanJob.max_retries"`)}
	}
	if _, ok := _c.mutation.TimeoutMs(); !ok {
		return &ValidationError{Name: "timeout_ms", err: errors.New(`ent: missing required field "IpScanJob.timeout_ms"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "IpScanJob.concurrency"`)}
	}
	if _, ok := _c.mutation.SkipReverseDNS(); !ok {
		return &ValidationError{Name: "skip_reverse_dns", err: errors.New(`ent: missing required field "IpScanJob.skip_reverse_dns"`)}
	}
	if _, ok := _c.mutation.TCPProbePorts(); !ok {
		return &ValidationError{Name: "tcp_probe_ports", err: errors.New(`ent: missing required field "IpScanJob.tcp_probe_ports"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := ipscanjob.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "IpScanJob.id": %w`, err)}
		}
	}
	if len(_c.mutation.SubnetIDs()) == 0 {
		return &ValidationError{Name: "subnet", err: errors.New(`ent: missing required edge "IpScanJob.subnet"`)}
	}
	return nil
}

func (_c *IpScanJobCreate) sqlSave(ctx context.Context) (*IpScanJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IpScanJob.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IpScanJobCreate) createSpec() (*IpScanJob, *sqlgraph.CreateSpec) {
	var (
		_node = &IpScanJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ipscanjob.Table, sqlgraph.NewFieldSpec(ipscanjob.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(ipscanjob.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(ipscanjob.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(ipscanjob.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(ipscanjob.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(ipscanjob.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(ipscanjob.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ipscanjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(ipscanjob.FieldProgress, field.TypeInt32, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.StatusMessage(); ok {
		_spec.SetField(ipscanjob.FieldStatusMessage, field.TypeString, value)
		_node.StatusMessage = value
	}
	if value, ok := _c.mutation.TotalAddresses(); ok {
		_spec.SetField(ipscanjob.FieldTotalAddresses, field.TypeInt64, value)
		_node.TotalAddresses = value
	}
	if value, ok := _c.mutation.ScannedCount(); ok {
		_spec.SetField(ipscanjob.FieldScannedCount, field.TypeInt64, value)
		_node.ScannedCount = value
	}
	if value, ok := _c.mutation.AliveCount(); ok {
		_spec.SetField(ipscanjob.FieldAliveCount, field.TypeInt64, value)
		_node.AliveCount = value
	}
	if value, ok := _c.mutation.NewCount(); ok {
		_spec.SetField(ipscanjob.FieldNewCount, field.TypeInt64, value)
		_node.NewCount = value
	}
	if value, ok := _c.mutation.UpdatedCount(); ok {
		_spec.SetField(ipscanjob.FieldUpdatedCount, field.TypeInt64, value)
		_node.UpdatedCount = value
	}
	if value, ok := _c.mutation.TriggeredBy(); ok {
		_spec.SetField(ipscanjob.FieldTriggeredBy, field.TypeEnum, value)
		_node.TriggeredBy = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(ipscanjob.FieldRetryCount, field.TypeInt32, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.MaxRetries(); ok {
		_spec.SetField(ipscanjob.FieldMaxRetries, field.TypeInt32, value)
		_node.MaxRetries = value
	}
	if value, ok := _c.mutation.NextRetryAt(); ok {
		_spec.SetField(ipscanjob.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = &value
	}
	if value, ok := _c.mutation.TimeoutMs(); ok {
		_spec.SetField(ipscanjob.FieldTimeoutMs, field.TypeInt32, value)
		_node.TimeoutMs = value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(ipscanjob.FieldConcurrency, field.TypeInt32, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.SkipReverseDNS(); ok {
		_spec.SetField(ipscanjob.FieldSkipReverseDNS, field.TypeBool, value)
		_node.SkipReverseDNS = value
	}
	if value, ok := _c.mutation.TCPProbePorts(); ok {
		_spec.SetField(ipscanjob.FieldTCPProbePorts, field.TypeString, value)
		_node.TCPProbePorts = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(ipscanjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(ipscanjob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := _c.mutation.SubnetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ipscanjob.SubnetTable,
			Columns: []string{ipscanjob.SubnetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subnet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubnetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IpScanJob.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IpScanJobUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *IpScanJobCreate) OnConflict(opts ...sql.ConflictOption) *IpScanJobUpsertOne {
	_c.conflict = opts
	return &IpScanJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IpScanJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IpScanJobCreate) OnConflictColumns(columns ...string) *IpScanJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IpScanJobUpsertOne{
		create: _c,
	}
}

type (
	// IpScanJobUpsertOne is the builder for "upsert"-ing
	//  one IpScanJob node.
	IpScanJobUpsertOne struct {
		create *IpScanJobCreate
	}

	// IpScanJobUpsert is the "OnConflict" setter.
	IpScanJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *IpScanJobUpsert) SetCreateBy(v uint32) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateCreateBy() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *IpScanJobUpsert) AddCreateBy(v uint32) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *IpScanJobUpsert) ClearCreateBy() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *IpScanJobUpsert) SetUpdateBy(v uint32) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateUpdateBy() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *IpScanJobUpsert) AddUpdateBy(v uint32) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *IpScanJobUpsert) ClearUpdateBy() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *IpScanJobUpsert) SetUpdateTime(v time.Time) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateUpdateTime() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *IpScanJobUpsert) ClearUpdateTime() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *IpScanJobUpsert) SetDeleteTime(v time.Time) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateDeleteTime() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *IpScanJobUpsert) ClearDeleteTime() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldDeleteTime)
	return u
}

// SetSubnetID sets the "subnet_id" field.
func (u *IpScanJobUpsert) SetSubnetID(v string) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldSubnetID, v)
	return u
}

// UpdateSubnetID sets the "subnet_id" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateSubnetID() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldSubnetID)
	return u
}

// SetStatus sets the "status" field.
func (u *IpScanJobUpsert) SetStatus(v ipscanjob.Status) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateStatus() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldStatus)
	return u
}

// SetProgress sets the "progress" field.
func (u *IpScanJobUpsert) SetProgress(v int32) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldProgress, v)
	return u
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateProgress() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldProgress)
	return u
}

// AddProgress adds v to the "progress" field.
func (u *IpScanJobUpsert) AddProgress(v int32) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldProgress, v)
	return u
}

// SetStatusMessage sets the "status_message" field.
func (u *IpScanJobUpsert) SetStatusMessage(v string) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldStatusMessage, v)
	return u
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateStatusMessage() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldStatusMessage)
	return u
}

// ClearStatusMessage clears the value of the "status_message" field.
func (u *IpScanJobUpsert) ClearStatusMessage() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldStatusMessage)
	return u
}

// SetTotalAddresses sets the "total_addresses" field.
func (u *IpScanJobUpsert) SetTotalAddresses(v int64) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldTotalAddresses, v)
	return u
}

// UpdateTotalAddresses sets the "total_addresses" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateTotalAddresses() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldTotalAddresses)
	return u
}

// AddTotalAddresses adds v to the "total_addresses" field.
func (u *IpScanJobUpsert) AddTotalAddresses(v int64) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldTotalAddresses, v)
	return u
}

// SetScannedCount sets the "scanned_count" field.
func (u *IpScanJobUpsert) SetScannedCount(v int64) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldScannedCount, v)
	return u
}

// UpdateScannedCount sets the "scanned_count" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateScannedCount() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldScannedCount)
	return u
}

// AddScannedCount adds v to the "scanned_count" field.
func (u *IpScanJobUpsert) AddScannedCount(v int64) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldScannedCount, v)
	return u
}

// SetAliveCount sets the "alive_count" field.
func (u *IpScanJobUpsert) SetAliveCount(v int64) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldAliveCount, v)
	return u
}

// UpdateAliveCount sets the "alive_count" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateAliveCount() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldAliveCount)
	return u
}

// AddAliveCount adds v to the "alive_count" field.
func (u *IpScanJobUpsert) AddAliveCount(v int64) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldAliveCount, v)
	return u
}

// SetNewCount sets the "new_count" field.
func (u *IpScanJobUpsert) SetNewCount(v int64) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldNewCount, v)
	return u
}

// UpdateNewCount sets the "new_count" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateNewCount() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldNewCount)
	return u
}

// AddNewCount adds v to the "new_count" field.
func (u *IpScanJobUpsert) AddNewCount(v int64) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldNewCount, v)
	return u
}

// SetUpdatedCount sets the "updated_count" field.
func (u *IpScanJobUpsert) SetUpdatedCount(v int64) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldUpdatedCount, v)
	return u
}

// UpdateUpdatedCount sets the "updated_count" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateUpdatedCount() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldUpdatedCount)
	return u
}

// AddUpdatedCount adds v to the "updated_count" field.
func (u *IpScanJobUpsert) AddUpdatedCount(v int64) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldUpdatedCount, v)
	return u
}

// SetTriggeredBy sets the "triggered_by" field.
func (u *IpScanJobUpsert) SetTriggeredBy(v ipscanjob.TriggeredBy) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldTriggeredBy, v)
	return u
}

// UpdateTriggeredBy sets the "triggered_by" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateTriggeredBy() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldTriggeredBy)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *IpScanJobUpsert) SetRetryCount(v int32) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateRetryCount() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *IpScanJobUpsert) AddRetryCount(v int32) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldRetryCount, v)
	return u
}

// SetMaxRetries sets the "max_retries" field.
func (u *IpScanJobUpsert) SetMaxRetries(v int32) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldMaxRetries, v)
	return u
}

// UpdateMaxRetries sets the "max_retries" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateMaxRetries() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldMaxRetries)
	return u
}

// AddMaxRetries adds v to the "max_retries" field.
func (u *IpScanJobUpsert) AddMaxRetries(v int32) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldMaxRetries, v)
	return u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *IpScanJobUpsert) SetNextRetryAt(v time.Time) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldNextRetryAt, v)
	return u
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateNextRetryAt() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldNextRetryAt)
	return u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *IpScanJobUpsert) ClearNextRetryAt() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldNextRetryAt)
	return u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (u *IpScanJobUpsert) SetTimeoutMs(v int32) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldTimeoutMs, v)
	return u
}

// UpdateTimeoutMs sets the "timeout_ms" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateTimeoutMs() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldTimeoutMs)
	return u
}

// AddTimeoutMs adds v to the "timeout_ms" field.
func (u *IpScanJobUpsert) AddTimeoutMs(v int32) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldTimeoutMs, v)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *IpScanJobUpsert) SetConcurrency(v int32) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateConcurrency() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *IpScanJobUpsert) AddConcurrency(v int32) *IpScanJobUpsert {
	u.Add(ipscanjob.FieldConcurrency, v)
	return u
}

// SetSkipReverseDNS sets the "skip_reverse_dns" field.
func (u *IpScanJobUpsert) SetSkipReverseDNS(v bool) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldSkipReverseDNS, v)
	return u
}

// UpdateSkipReverseDNS sets the "skip_reverse_dns" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateSkipReverseDNS() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldSkipReverseDNS)
	return u
}

// SetTCPProbePorts sets the "tcp_probe_ports" field.
func (u *IpScanJobUpsert) SetTCPProbePorts(v string) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldTCPProbePorts, v)
	return u
}

// UpdateTCPProbePorts sets the "tcp_probe_ports" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateTCPProbePorts() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldTCPProbePorts)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *IpScanJobUpsert) SetStartedAt(v time.Time) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateStartedAt() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *IpScanJobUpsert) ClearStartedAt() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *IpScanJobUpsert) SetCompletedAt(v time.Time) *IpScanJobUpsert {
	u.Set(ipscanjob.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *IpScanJobUpsert) UpdateCompletedAt() *IpScanJobUpsert {
	u.SetExcluded(ipscanjob.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *IpScanJobUpsert) ClearCompletedAt() *IpScanJobUpsert {
	u.SetNull(ipscanjob.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IpScanJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ipscanjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IpScanJobUpsertOne) UpdateNewValues() *IpScanJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ipscanjob.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(ipscanjob.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(ipscanjob.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IpScanJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IpScanJobUpsertOne) Ignore() *IpScanJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IpScanJobUpsertOne) DoNothing() *IpScanJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IpScanJobCreate.OnConflict
// documentation for more info.
func (u *IpScanJobUpsertOne) Update(set func(*IpScanJobUpsert)) *IpScanJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IpScanJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *IpScanJobUpsertOne) SetCreateBy(v uint32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *IpScanJobUpsertOne) AddCreateBy(v uint32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateCreateBy() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *IpScanJobUpsertOne) ClearCreateBy() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *IpScanJobUpsertOne) SetUpdateBy(v uint32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *IpScanJobUpsertOne) AddUpdateBy(v uint32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateUpdateBy() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *IpScanJobUpsertOne) ClearUpdateBy() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *IpScanJobUpsertOne) SetUpdateTime(v time.Time) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateUpdateTime() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *IpScanJobUpsertOne) ClearUpdateTime() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *IpScanJobUpsertOne) SetDeleteTime(v time.Time) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateDeleteTime() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *IpScanJobUpsertOne) ClearDeleteTime() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSubnetID sets the "subnet_id" field.
func (u *IpScanJobUpsertOne) SetSubnetID(v string) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetSubnetID(v)
	})
}

// UpdateSubnetID sets the "subnet_id" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateSubnetID() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateSubnetID()
	})
}

// SetStatus sets the "status" field.
func (u *IpScanJobUpsertOne) SetStatus(v ipscanjob.Status) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateStatus() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateStatus()
	})
}

// SetProgress sets the "progress" field.
func (u *IpScanJobUpsertOne) SetProgress(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetProgress(v)
	})
}

// AddProgress adds v to the "progress" field.
func (u *IpScanJobUpsertOne) AddProgress(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateProgress() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateProgress()
	})
}

// SetStatusMessage sets the "status_message" field.
func (u *IpScanJobUpsertOne) SetStatusMessage(v string) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetStatusMessage(v)
	})
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateStatusMessage() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateStatusMessage()
	})
}

// ClearStatusMessage clears the value of the "status_message" field.
func (u *IpScanJobUpsertOne) ClearStatusMessage() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearStatusMessage()
	})
}

// SetTotalAddresses sets the "total_addresses" field.
func (u *IpScanJobUpsertOne) SetTotalAddresses(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTotalAddresses(v)
	})
}

// AddTotalAddresses adds v to the "total_addresses" field.
func (u *IpScanJobUpsertOne) AddTotalAddresses(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddTotalAddresses(v)
	})
}

// UpdateTotalAddresses sets the "total_addresses" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateTotalAddresses() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTotalAddresses()
	})
}

// SetScannedCount sets the "scanned_count" field.
func (u *IpScanJobUpsertOne) SetScannedCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetScannedCount(v)
	})
}

// AddScannedCount adds v to the "scanned_count" field.
func (u *IpScanJobUpsertOne) AddScannedCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddScannedCount(v)
	})
}

// UpdateScannedCount sets the "scanned_count" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateScannedCount() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateScannedCount()
	})
}

// SetAliveCount sets the "alive_count" field.
func (u *IpScanJobUpsertOne) SetAliveCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetAliveCount(v)
	})
}

// AddAliveCount adds v to the "alive_count" field.
func (u *IpScanJobUpsertOne) AddAliveCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddAliveCount(v)
	})
}

// UpdateAliveCount sets the "alive_count" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateAliveCount() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateAliveCount()
	})
}

// SetNewCount sets the "new_count" field.
func (u *IpScanJobUpsertOne) SetNewCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetNewCount(v)
	})
}

// AddNewCount adds v to the "new_count" field.
func (u *IpScanJobUpsertOne) AddNewCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddNewCount(v)
	})
}

// UpdateNewCount sets the "new_count" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateNewCount() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateNewCount()
	})
}

// SetUpdatedCount sets the "updated_count" field.
func (u *IpScanJobUpsertOne) SetUpdatedCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetUpdatedCount(v)
	})
}

// AddUpdatedCount adds v to the "updated_count" field.
func (u *IpScanJobUpsertOne) AddUpdatedCount(v int64) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddUpdatedCount(v)
	})
}

// UpdateUpdatedCount sets the "updated_count" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateUpdatedCount() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateUpdatedCount()
	})
}

// SetTriggeredBy sets the "triggered_by" field.
func (u *IpScanJobUpsertOne) SetTriggeredBy(v ipscanjob.TriggeredBy) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTriggeredBy(v)
	})
}

// UpdateTriggeredBy sets the "triggered_by" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateTriggeredBy() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTriggeredBy()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *IpScanJobUpsertOne) SetRetryCount(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *IpScanJobUpsertOne) AddRetryCount(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateRetryCount() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateRetryCount()
	})
}

// SetMaxRetries sets the "max_retries" field.
func (u *IpScanJobUpsertOne) SetMaxRetries(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetMaxRetries(v)
	})
}

// AddMaxRetries adds v to the "max_retries" field.
func (u *IpScanJobUpsertOne) AddMaxRetries(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddMaxRetries(v)
	})
}

// UpdateMaxRetries sets the "max_retries" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateMaxRetries() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateMaxRetries()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *IpScanJobUpsertOne) SetNextRetryAt(v time.Time) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateNextRetryAt() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *IpScanJobUpsertOne) ClearNextRetryAt() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearNextRetryAt()
	})
}

// SetTimeoutMs sets the "timeout_ms" field.
func (u *IpScanJobUpsertOne) SetTimeoutMs(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTimeoutMs(v)
	})
}

// AddTimeoutMs adds v to the "timeout_ms" field.
func (u *IpScanJobUpsertOne) AddTimeoutMs(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddTimeoutMs(v)
	})
}

// UpdateTimeoutMs sets the "timeout_ms" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateTimeoutMs() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTimeoutMs()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *IpScanJobUpsertOne) SetConcurrency(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *IpScanJobUpsertOne) AddConcurrency(v int32) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateConcurrency() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateConcurrency()
	})
}

// SetSkipReverseDNS sets the "skip_reverse_dns" field.
func (u *IpScanJobUpsertOne) SetSkipReverseDNS(v bool) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetSkipReverseDNS(v)
	})
}

// UpdateSkipReverseDNS sets the "skip_reverse_dns" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateSkipReverseDNS() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateSkipReverseDNS()
	})
}

// SetTCPProbePorts sets the "tcp_probe_ports" field.
func (u *IpScanJobUpsertOne) SetTCPProbePorts(v string) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTCPProbePorts(v)
	})
}

// UpdateTCPProbePorts sets the "tcp_probe_ports" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateTCPProbePorts() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTCPProbePorts()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *IpScanJobUpsertOne) SetStartedAt(v time.Time) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateStartedAt() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *IpScanJobUpsertOne) ClearStartedAt() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *IpScanJobUpsertOne) SetCompletedAt(v time.Time) *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *IpScanJobUpsertOne) UpdateCompletedAt() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *IpScanJobUpsertOne) ClearCompletedAt() *IpScanJobUpsertOne {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *IpScanJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IpScanJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IpScanJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IpScanJobUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IpScanJobUpsertOne.ID is not supported by MySQL driver. Use IpScanJobUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IpScanJobUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IpScanJobCreateBulk is the builder for creating many IpScanJob entities in bulk.
type IpScanJobCreateBulk struct {
	config
	err      error
	builders []*IpScanJobCreate
	conflict []sql.ConflictOption
}

// Save creates the IpScanJob entities in the database.
func (_c *IpScanJobCreateBulk) Save(ctx context.Context) ([]*IpScanJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IpScanJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IpScanJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IpScanJobCreateBulk) SaveX(ctx context.Context) []*IpScanJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IpScanJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IpScanJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IpScanJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IpScanJobUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *IpScanJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *IpScanJobUpsertBulk {
	_c.conflict = opts
	return &IpScanJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IpScanJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IpScanJobCreateBulk) OnConflictColumns(columns ...string) *IpScanJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IpScanJobUpsertBulk{
		create: _c,
	}
}

// IpScanJobUpsertBulk is the builder for "upsert"-ing
// a bulk of IpScanJob nodes.
type IpScanJobUpsertBulk struct {
	create *IpScanJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IpScanJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ipscanjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IpScanJobUpsertBulk) UpdateNewValues() *IpScanJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ipscanjob.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(ipscanjob.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(ipscanjob.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IpScanJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IpScanJobUpsertBulk) Ignore() *IpScanJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IpScanJobUpsertBulk) DoNothing() *IpScanJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IpScanJobCreateBulk.OnConflict
// documentation for more info.
func (u *IpScanJobUpsertBulk) Update(set func(*IpScanJobUpsert)) *IpScanJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IpScanJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *IpScanJobUpsertBulk) SetCreateBy(v uint32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *IpScanJobUpsertBulk) AddCreateBy(v uint32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateCreateBy() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *IpScanJobUpsertBulk) ClearCreateBy() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *IpScanJobUpsertBulk) SetUpdateBy(v uint32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *IpScanJobUpsertBulk) AddUpdateBy(v uint32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateUpdateBy() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *IpScanJobUpsertBulk) ClearUpdateBy() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *IpScanJobUpsertBulk) SetUpdateTime(v time.Time) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateUpdateTime() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *IpScanJobUpsertBulk) ClearUpdateTime() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *IpScanJobUpsertBulk) SetDeleteTime(v time.Time) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateDeleteTime() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *IpScanJobUpsertBulk) ClearDeleteTime() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSubnetID sets the "subnet_id" field.
func (u *IpScanJobUpsertBulk) SetSubnetID(v string) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetSubnetID(v)
	})
}

// UpdateSubnetID sets the "subnet_id" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateSubnetID() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateSubnetID()
	})
}

// SetStatus sets the "status" field.
func (u *IpScanJobUpsertBulk) SetStatus(v ipscanjob.Status) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateStatus() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateStatus()
	})
}

// SetProgress sets the "progress" field.
func (u *IpScanJobUpsertBulk) SetProgress(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetProgress(v)
	})
}

// AddProgress adds v to the "progress" field.
func (u *IpScanJobUpsertBulk) AddProgress(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateProgress() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateProgress()
	})
}

// SetStatusMessage sets the "status_message" field.
func (u *IpScanJobUpsertBulk) SetStatusMessage(v string) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetStatusMessage(v)
	})
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateStatusMessage() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateStatusMessage()
	})
}

// ClearStatusMessage clears the value of the "status_message" field.
func (u *IpScanJobUpsertBulk) ClearStatusMessage() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearStatusMessage()
	})
}

// SetTotalAddresses sets the "total_addresses" field.
func (u *IpScanJobUpsertBulk) SetTotalAddresses(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTotalAddresses(v)
	})
}

// AddTotalAddresses adds v to the "total_addresses" field.
func (u *IpScanJobUpsertBulk) AddTotalAddresses(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddTotalAddresses(v)
	})
}

// UpdateTotalAddresses sets the "total_addresses" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateTotalAddresses() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTotalAddresses()
	})
}

// SetScannedCount sets the "scanned_count" field.
func (u *IpScanJobUpsertBulk) SetScannedCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetScannedCount(v)
	})
}

// AddScannedCount adds v to the "scanned_count" field.
func (u *IpScanJobUpsertBulk) AddScannedCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddScannedCount(v)
	})
}

// UpdateScannedCount sets the "scanned_count" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateScannedCount() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateScannedCount()
	})
}

// SetAliveCount sets the "alive_count" field.
func (u *IpScanJobUpsertBulk) SetAliveCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetAliveCount(v)
	})
}

// AddAliveCount adds v to the "alive_count" field.
func (u *IpScanJobUpsertBulk) AddAliveCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddAliveCount(v)
	})
}

// UpdateAliveCount sets the "alive_count" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateAliveCount() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateAliveCount()
	})
}

// SetNewCount sets the "new_count" field.
func (u *IpScanJobUpsertBulk) SetNewCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetNewCount(v)
	})
}

// AddNewCount adds v to the "new_count" field.
func (u *IpScanJobUpsertBulk) AddNewCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddNewCount(v)
	})
}

// UpdateNewCount sets the "new_count" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateNewCount() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateNewCount()
	})
}

// SetUpdatedCount sets the "updated_count" field.
func (u *IpScanJobUpsertBulk) SetUpdatedCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetUpdatedCount(v)
	})
}

// AddUpdatedCount adds v to the "updated_count" field.
func (u *IpScanJobUpsertBulk) AddUpdatedCount(v int64) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddUpdatedCount(v)
	})
}

// UpdateUpdatedCount sets the "updated_count" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateUpdatedCount() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateUpdatedCount()
	})
}

// SetTriggeredBy sets the "triggered_by" field.
func (u *IpScanJobUpsertBulk) SetTriggeredBy(v ipscanjob.TriggeredBy) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTriggeredBy(v)
	})
}

// UpdateTriggeredBy sets the "triggered_by" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateTriggeredBy() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTriggeredBy()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *IpScanJobUpsertBulk) SetRetryCount(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *IpScanJobUpsertBulk) AddRetryCount(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateRetryCount() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateRetryCount()
	})
}

// SetMaxRetries sets the "max_retries" field.
func (u *IpScanJobUpsertBulk) SetMaxRetries(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetMaxRetries(v)
	})
}

// AddMaxRetries adds v to the "max_retries" field.
func (u *IpScanJobUpsertBulk) AddMaxRetries(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddMaxRetries(v)
	})
}

// UpdateMaxRetries sets the "max_retries" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateMaxRetries() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateMaxRetries()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *IpScanJobUpsertBulk) SetNextRetryAt(v time.Time) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateNextRetryAt() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *IpScanJobUpsertBulk) ClearNextRetryAt() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearNextRetryAt()
	})
}

// SetTimeoutMs sets the "timeout_ms" field.
func (u *IpScanJobUpsertBulk) SetTimeoutMs(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTimeoutMs(v)
	})
}

// AddTimeoutMs adds v to the "timeout_ms" field.
func (u *IpScanJobUpsertBulk) AddTimeoutMs(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddTimeoutMs(v)
	})
}

// UpdateTimeoutMs sets the "timeout_ms" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateTimeoutMs() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTimeoutMs()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *IpScanJobUpsertBulk) SetConcurrency(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *IpScanJobUpsertBulk) AddConcurrency(v int32) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateConcurrency() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateConcurrency()
	})
}

// SetSkipReverseDNS sets the "skip_reverse_dns" field.
func (u *IpScanJobUpsertBulk) SetSkipReverseDNS(v bool) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetSkipReverseDNS(v)
	})
}

// UpdateSkipReverseDNS sets the "skip_reverse_dns" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateSkipReverseDNS() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateSkipReverseDNS()
	})
}

// SetTCPProbePorts sets the "tcp_probe_ports" field.
func (u *IpScanJobUpsertBulk) SetTCPProbePorts(v string) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetTCPProbePorts(v)
	})
}

// UpdateTCPProbePorts sets the "tcp_probe_ports" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateTCPProbePorts() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateTCPProbePorts()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *IpScanJobUpsertBulk) SetStartedAt(v time.Time) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateStartedAt() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *IpScanJobUpsertBulk) ClearStartedAt() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *IpScanJobUpsertBulk) SetCompletedAt(v time.Time) *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *IpScanJobUpsertBulk) UpdateCompletedAt() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *IpScanJobUpsertBulk) ClearCompletedAt() *IpScanJobUpsertBulk {
	return u.Update(func(s *IpScanJobUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *IpScanJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IpScanJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IpScanJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IpScanJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
