// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/ipaddress"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/ipscanjob"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/location"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/subnet"
	"github.com/go-tangra/go-tangra-portal/app/ipam/service/internal/data/ent/vlan"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubnetQuery is the builder for querying Subnet entities.
type SubnetQuery struct {
	config
	ctx           *QueryContext
	order         []subnet.OrderOption
	inters        []Interceptor
	predicates    []predicate.Subnet
	withAddresses *IpAddressQuery
	withParent    *SubnetQuery
	withChildren  *SubnetQuery
	withVlan      *VlanQuery
	withLocation  *LocationQuery
	withScanJobs  *IpScanJobQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubnetQuery builder.
func (_q *SubnetQuery) Where(ps ...predicate.Subnet) *SubnetQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubnetQuery) Limit(limit int) *SubnetQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubnetQuery) Offset(offset int) *SubnetQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubnetQuery) Unique(unique bool) *SubnetQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubnetQuery) Order(o ...subnet.OrderOption) *SubnetQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAddresses chains the current query on the "addresses" edge.
func (_q *SubnetQuery) QueryAddresses() *IpAddressQuery {
	query := (&IpAddressClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subnet.Table, subnet.FieldID, selector),
			sqlgraph.To(ipaddress.Table, ipaddress.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subnet.AddressesTable, subnet.AddressesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (_q *SubnetQuery) QueryParent() *SubnetQuery {
	query := (&SubnetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subnet.Table, subnet.FieldID, selector),
			sqlgraph.To(subnet.Table, subnet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subnet.ParentTable, subnet.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (_q *SubnetQuery) QueryChildren() *SubnetQuery {
	query := (&SubnetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subnet.Table, subnet.FieldID, selector),
			sqlgraph.To(subnet.Table, subnet.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subnet.ChildrenTable, subnet.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVlan chains the current query on the "vlan" edge.
func (_q *SubnetQuery) QueryVlan() *VlanQuery {
	query := (&VlanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subnet.Table, subnet.FieldID, selector),
			sqlgraph.To(vlan.Table, vlan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, subnet.VlanTable, subnet.VlanColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocation chains the current query on the "location" edge.
func (_q *SubnetQuery) QueryLocation() *LocationQuery {
	query := (&LocationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subnet.Table, subnet.FieldID, selector),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, subnet.LocationTable, subnet.LocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScanJobs chains the current query on the "scan_jobs" edge.
func (_q *SubnetQuery) QueryScanJobs() *IpScanJobQuery {
	query := (&IpScanJobClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subnet.Table, subnet.FieldID, selector),
			sqlgraph.To(ipscanjob.Table, ipscanjob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subnet.ScanJobsTable, subnet.ScanJobsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Subnet entity from the query.
// Returns a *NotFoundError when no Subnet was found.
func (_q *SubnetQuery) First(ctx context.Context) (*Subnet, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subnet.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubnetQuery) FirstX(ctx context.Context) *Subnet {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Subnet ID from the query.
// Returns a *NotFoundError when no Subnet ID was found.
func (_q *SubnetQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subnet.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubnetQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Subnet entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Subnet entity is found.
// Returns a *NotFoundError when no Subnet entities are found.
func (_q *SubnetQuery) Only(ctx context.Context) (*Subnet, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subnet.Label}
	default:
		return nil, &NotSingularError{subnet.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubnetQuery) OnlyX(ctx context.Context) *Subnet {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Subnet ID in the query.
// Returns a *NotSingularError when more than one Subnet ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubnetQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subnet.Label}
	default:
		err = &NotSingularError{subnet.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubnetQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Subnets.
func (_q *SubnetQuery) All(ctx context.Context) ([]*Subnet, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Subnet, *SubnetQuery]()
	return withInterceptors[[]*Subnet](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubnetQuery) AllX(ctx context.Context) []*Subnet {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Subnet IDs.
func (_q *SubnetQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subnet.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubnetQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubnetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubnetQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubnetQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubnetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubnetQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubnetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubnetQuery) Clone() *SubnetQuery {
	if _q == nil {
		return nil
	}
	return &SubnetQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]subnet.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Subnet{}, _q.predicates...),
		withAddresses: _q.withAddresses.Clone(),
		withParent:    _q.withParent.Clone(),
		withChildren:  _q.withChildren.Clone(),
		withVlan:      _q.withVlan.Clone(),
		withLocation:  _q.withLocation.Clone(),
		withScanJobs:  _q.withScanJobs.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAddresses tells the query-builder to eager-load the nodes that are connected to
// the "addresses" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubnetQuery) WithAddresses(opts ...func(*IpAddressQuery)) *SubnetQuery {
	query := (&IpAddressClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAddresses = query
	return _q
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubnetQuery) WithParent(opts ...func(*SubnetQuery)) *SubnetQuery {
	query := (&SubnetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubnetQuery) WithChildren(opts ...func(*SubnetQuery)) *SubnetQuery {
	query := (&SubnetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildren = query
	return _q
}

// WithVlan tells the query-builder to eager-load the nodes that are connected to
// the "vlan" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubnetQuery) WithVlan(opts ...func(*VlanQuery)) *SubnetQuery {
	query := (&VlanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVlan = query
	return _q
}

// WithLocation tells the query-builder to eager-load the nodes that are connected to
// the "location" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubnetQuery) WithLocation(opts ...func(*LocationQuery)) *SubnetQuery {
	query := (&LocationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocation = query
	return _q
}

// WithScanJobs tells the query-builder to eager-load the nodes that are connected to
// the "scan_jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubnetQuery) WithScanJobs(opts ...func(*IpScanJobQuery)) *SubnetQuery {
	query := (&IpScanJobClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScanJobs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateBy uint32 `json:"create_by,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Subnet.Query().
//		GroupBy(subnet.FieldCreateBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubnetQuery) GroupBy(field string, fields ...string) *SubnetGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubnetGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subnet.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateBy uint32 `json:"create_by,omitempty"`
//	}
//
//	client.Subnet.Query().
//		Select(subnet.FieldCreateBy).
//		Scan(ctx, &v)
func (_q *SubnetQuery) Select(fields ...string) *SubnetSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubnetSelect{SubnetQuery: _q}
	sbuild.label = subnet.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubnetSelect configured with the given aggregations.
func (_q *SubnetQuery) Aggregate(fns ...AggregateFunc) *SubnetSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubnetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subnet.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if subnet.Policy == nil {
		return errors.New("ent: uninitialized subnet.Policy (forgotten import ent/runtime?)")
	}
	if err := subnet.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *SubnetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Subnet, error) {
	var (
		nodes       = []*Subnet{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withAddresses != nil,
			_q.withParent != nil,
			_q.withChildren != nil,
			_q.withVlan != nil,
			_q.withLocation != nil,
			_q.withScanJobs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Subnet).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Subnet{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAddresses; query != nil {
		if err := _q.loadAddresses(ctx, query, nodes,
			func(n *Subnet) { n.Edges.Addresses = []*IpAddress{} },
			func(n *Subnet, e *IpAddress) { n.Edges.Addresses = append(n.Edges.Addresses, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *Subnet, e *Subnet) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChildren; query != nil {
		if err := _q.loadChildren(ctx, query, nodes,
			func(n *Subnet) { n.Edges.Children = []*Subnet{} },
			func(n *Subnet, e *Subnet) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVlan; query != nil {
		if err := _q.loadVlan(ctx, query, nodes, nil,
			func(n *Subnet, e *Vlan) { n.Edges.Vlan = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLocation; query != nil {
		if err := _q.loadLocation(ctx, query, nodes, nil,
			func(n *Subnet, e *Location) { n.Edges.Location = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withScanJobs; query != nil {
		if err := _q.loadScanJobs(ctx, query, nodes,
			func(n *Subnet) { n.Edges.ScanJobs = []*IpScanJob{} },
			func(n *Subnet, e *IpScanJob) { n.Edges.ScanJobs = append(n.Edges.ScanJobs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubnetQuery) loadAddresses(ctx context.Context, query *IpAddressQuery, nodes []*Subnet, init func(*Subnet), assign func(*Subnet, *IpAddress)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Subnet)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ipaddress.FieldSubnetID)
	}
	query.Where(predicate.IpAddress(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subnet.AddressesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SubnetID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "subnet_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *SubnetQuery) loadParent(ctx context.Context, query *SubnetQuery, nodes []*Subnet, init func(*Subnet), assign func(*Subnet, *Subnet)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Subnet)
	for i := range nodes {
		fk := nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subnet.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubnetQuery) loadChildren(ctx context.Context, query *SubnetQuery, nodes []*Subnet, init func(*Subnet), assign func(*Subnet, *Subnet)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Subnet)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(subnet.FieldParentID)
	}
	query.Where(predicate.Subnet(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subnet.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *SubnetQuery) loadVlan(ctx context.Context, query *VlanQuery, nodes []*Subnet, init func(*Subnet), assign func(*Subnet, *Vlan)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Subnet)
	for i := range nodes {
		fk := nodes[i].VlanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(vlan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vlan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubnetQuery) loadLocation(ctx context.Context, query *LocationQuery, nodes []*Subnet, init func(*Subnet), assign func(*Subnet, *Location)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Subnet)
	for i := range nodes {
		fk := nodes[i].LocationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(location.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "location_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubnetQuery) loadScanJobs(ctx context.Context, query *IpScanJobQuery, nodes []*Subnet, init func(*Subnet), assign func(*Subnet, *IpScanJob)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Subnet)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ipscanjob.FieldSubnetID)
	}
	query.Where(predicate.IpScanJob(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subnet.ScanJobsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SubnetID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "subnet_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SubnetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubnetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subnet.Table, subnet.Columns, sqlgraph.NewFieldSpec(subnet.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subnet.FieldID)
		for i := range fields {
			if fields[i] != subnet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withParent != nil {
			_spec.Node.AddColumnOnce(subnet.FieldParentID)
		}
		if _q.withVlan != nil {
			_spec.Node.AddColumnOnce(subnet.FieldVlanID)
		}
		if _q.withLocation != nil {
			_spec.Node.AddColumnOnce(subnet.FieldLocationID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubnetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subnet.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subnet.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubnetQuery) ForUpdate(opts ...sql.LockOption) *SubnetQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubnetQuery) ForShare(opts ...sql.LockOption) *SubnetQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *SubnetQuery) Modify(modifiers ...func(s *sql.Selector)) *SubnetSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// SubnetGroupBy is the group-by builder for Subnet entities.
type SubnetGroupBy struct {
	selector
	build *SubnetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubnetGroupBy) Aggregate(fns ...AggregateFunc) *SubnetGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubnetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubnetQuery, *SubnetGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubnetGroupBy) sqlScan(ctx context.Context, root *SubnetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubnetSelect is the builder for selecting fields of Subnet entities.
type SubnetSelect struct {
	*SubnetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubnetSelect) Aggregate(fns ...AggregateFunc) *SubnetSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubnetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubnetQuery, *SubnetSelect](ctx, _s.SubnetQuery, _s, _s.inters, v)
}

func (_s *SubnetSelect) sqlScan(ctx context.Context, root *SubnetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *SubnetSelect) Modify(modifiers ...func(s *sql.Selector)) *SubnetSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
