// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/cert"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/data"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/event"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/server"
	"github.com/go-tangra/go-tangra-portal/app/deployer/service/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

import (
	_ "github.com/go-tangra/go-tangra-portal/app/deployer/service/pkg/deploy/providers"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application.
//
// Parameters:
//   - *bootstrap.Context: bootstrap context
//
// Returns:
//   - *kratos.App: constructed application instance
//   - func(): cleanup function to run on shutdown
//   - error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	deploymentTargetRepo := data.NewDeploymentTargetRepo(context, entClient)
	targetConfigurationRepo := data.NewTargetConfigurationRepo(context, entClient)
	deploymentTargetService := service.NewDeploymentTargetService(context, deploymentTargetRepo, targetConfigurationRepo)
	targetConfigurationService := service.NewTargetConfigurationService(context, targetConfigurationRepo)
	deploymentJobRepo := data.NewDeploymentJobRepo(context, entClient)
	deploymentHistoryRepo := data.NewDeploymentHistoryRepo(context, entClient)
	deploymentJobService := service.NewDeploymentJobService(context, deploymentJobRepo, deploymentTargetRepo, targetConfigurationRepo, deploymentHistoryRepo)
	deploymentService := service.NewDeploymentService(context, deploymentJobRepo, deploymentTargetRepo, targetConfigurationRepo, deploymentHistoryRepo, targetConfigurationService)
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	statisticsService := service.NewStatisticsService(context, statisticsRepo)
	grpcServer := server.NewGRPCServer(context, certManager, auditLogRepo, deploymentTargetService, targetConfigurationService, deploymentJobService, deploymentService, statisticsService)
	client, cleanup2, err := data.NewRedisClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handler := event.NewHandler(context, deploymentTargetRepo, deploymentJobRepo)
	subscriber := event.NewSubscriber(context, client, handler)
	lcmClient, cleanup3, err := data.NewLcmClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobExecutor := service.NewJobExecutor(context, deploymentJobRepo, targetConfigurationRepo, deploymentHistoryRepo, targetConfigurationService, lcmClient)
	app := newApp(context, grpcServer, subscriber, jobExecutor)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
