// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	bootstrap2 "github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/bootstrap"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/cert"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/event"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/server"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/service"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/service/providers"
	"github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/webhook"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

import (
	_ "github.com/go-tangra/go-tangra-portal/app/lcm/service/internal/data/ent/runtime"
	_ "github.com/go-tangra/go-tangra-portal/app/lcm/service/pkg/dns/init"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application.
//
// Parameters:
//   - *bootstrap.Context: *bootstrap.Context: bootstrap context
//
// Returns:
//   - *kratos.App: *kratos.App: constructed application instance
//   - func(): func(): cleanup function to run on shutdown
//   - error: error: possible construction error
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	systemService := service.NewSystemService(context)
	lcmClientRepo := data.NewLcmClientRepo(context, entClient)
	mtlsCertificateRequestRepo := data.NewMtlsCertificateRequestRepo(context, entClient)
	mtlsCertificateRepo := data.NewMtlsCertificateRepo(context, entClient)
	tenantSecretRepo := data.NewTenantSecretRepo(context, entClient)
	client, cleanup2, err := data.NewRedisClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	lcmClientService := service.NewLcmClientService(context, certManager, lcmClientRepo, mtlsCertificateRequestRepo, mtlsCertificateRepo, tenantSecretRepo, client)
	issuerRepo := data.NewIssuerRepo(context, entClient)
	issuerService := service.NewIssuerService(context, issuerRepo, lcmClientRepo, mtlsCertificateRepo)
	issuedCertificateRepo := data.NewIssuedCertificateRepo(context, entClient)
	publisher := event.NewPublisher(context, client)
	certificateJobService := service.NewCertificateJobService(context, issuerRepo, lcmClientRepo, mtlsCertificateRepo, issuedCertificateRepo, publisher)
	tenantSecretService := service.NewTenantSecretService(context, tenantSecretRepo, lcmClientRepo)
	auditLogService := service.NewAuditLogService(context, auditLogRepo, lcmClientRepo)
	mtlsCertService, err := service.NewMtlsCertService(context, mtlsCertificateRepo, lcmClientRepo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	certificatePermissionRepo := data.NewCertificatePermissionRepo(context, entClient)
	certificatePermissionService := service.NewCertificatePermissionService(context, certificatePermissionRepo, lcmClientRepo, issuedCertificateRepo)
	mtlsCertificateRequestService, err := service.NewMtlsCertificateRequestService(context, mtlsCertificateRequestRepo, mtlsCertificateRepo, lcmClientRepo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	statisticsService := service.NewStatisticsService(context, statisticsRepo)
	grpcServer := server.NewGRPCServer(context, certManager, auditLogRepo, systemService, lcmClientService, issuerService, certificateJobService, tenantSecretService, auditLogService, mtlsCertService, certificatePermissionService, mtlsCertificateRequestService, statisticsService)
	bootstrapService, err := bootstrap2.NewBootstrapService(context, mtlsCertificateRepo, lcmClientRepo)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	renewalConfig := providers.ProvideRenewalConfig(context)
	certificateRenewalRepo := data.NewCertificateRenewalRepo(context, entClient)
	renewalScheduler := service.NewRenewalScheduler(context, renewalConfig, issuedCertificateRepo, certificateRenewalRepo, issuerRepo, lcmClientRepo, certificateJobService, publisher)
	webhookService, err := webhook.NewService(context, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, grpcServer, bootstrapService, renewalScheduler, webhookService)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
